package cn.arp.trend.entity.biz;

import java.util.Date;

public class CasAcademicianForeign {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_academician_foreign.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_academician_foreign.stat_year
     *
     * @mbggenerated
     */
    private String statYear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_academician_foreign.desc
     *
     * @mbggenerated
     */
    private String desc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_academician_foreign.pid
     *
     * @mbggenerated
     */
    private Long pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_academician_foreign.cid
     *
     * @mbggenerated
     */
    private Long cid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_academician_foreign.metaid
     *
     * @mbggenerated
     */
    private Long metaid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_academician_foreign.zsys
     *
     * @mbggenerated
     */
    private String zsys;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_academician_foreign.xuebu
     *
     * @mbggenerated
     */
    private String xuebu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_academician_foreign.xingming
     *
     * @mbggenerated
     */
    private String xingming;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_academician_foreign.dxnf
     *
     * @mbggenerated
     */
    private String dxnf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_academician_foreign.xingbie
     *
     * @mbggenerated
     */
    private String xingbie;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_academician_foreign.guoji
     *
     * @mbggenerated
     */
    private String guoji;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_academician_foreign.csny
     *
     * @mbggenerated
     */
    private String csny;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_academician_foreign.nianling
     *
     * @mbggenerated
     */
    private String nianling;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_academician_foreign.qssj
     *
     * @mbggenerated
     */
    private String qssj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_academician_foreign.chushengdi
     *
     * @mbggenerated
     */
    private String chushengdi;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_academician_foreign.byyx1
     *
     * @mbggenerated
     */
    private String byyx1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_academician_foreign.byyx2
     *
     * @mbggenerated
     */
    private String byyx2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_academician_foreign.byyx3
     *
     * @mbggenerated
     */
    private String byyx3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_academician_foreign.zhuanye
     *
     * @mbggenerated
     */
    private String zhuanye;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_academician_foreign.gzdw
     *
     * @mbggenerated
     */
    private String gzdw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_academician_foreign.datasource_type
     *
     * @mbggenerated
     */
    private String datasourceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_academician_foreign.etl_datasource
     *
     * @mbggenerated
     */
    private String etlDatasource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_academician_foreign.firstinput_time
     *
     * @mbggenerated
     */
    private Date firstinputTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_academician_foreign.laterupdate_time
     *
     * @mbggenerated
     */
    private Date laterupdateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_academician_foreign.id
     *
     * @return the value of cas_academician_foreign.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_academician_foreign.id
     *
     * @param id the value for cas_academician_foreign.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_academician_foreign.stat_year
     *
     * @return the value of cas_academician_foreign.stat_year
     *
     * @mbggenerated
     */
    public String getStatYear() {
        return statYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_academician_foreign.stat_year
     *
     * @param statYear the value for cas_academician_foreign.stat_year
     *
     * @mbggenerated
     */
    public void setStatYear(String statYear) {
        this.statYear = statYear == null ? null : statYear.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_academician_foreign.desc
     *
     * @return the value of cas_academician_foreign.desc
     *
     * @mbggenerated
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_academician_foreign.desc
     *
     * @param desc the value for cas_academician_foreign.desc
     *
     * @mbggenerated
     */
    public void setDesc(String desc) {
        this.desc = desc == null ? null : desc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_academician_foreign.pid
     *
     * @return the value of cas_academician_foreign.pid
     *
     * @mbggenerated
     */
    public Long getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_academician_foreign.pid
     *
     * @param pid the value for cas_academician_foreign.pid
     *
     * @mbggenerated
     */
    public void setPid(Long pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_academician_foreign.cid
     *
     * @return the value of cas_academician_foreign.cid
     *
     * @mbggenerated
     */
    public Long getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_academician_foreign.cid
     *
     * @param cid the value for cas_academician_foreign.cid
     *
     * @mbggenerated
     */
    public void setCid(Long cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_academician_foreign.metaid
     *
     * @return the value of cas_academician_foreign.metaid
     *
     * @mbggenerated
     */
    public Long getMetaid() {
        return metaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_academician_foreign.metaid
     *
     * @param metaid the value for cas_academician_foreign.metaid
     *
     * @mbggenerated
     */
    public void setMetaid(Long metaid) {
        this.metaid = metaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_academician_foreign.zsys
     *
     * @return the value of cas_academician_foreign.zsys
     *
     * @mbggenerated
     */
    public String getZsys() {
        return zsys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_academician_foreign.zsys
     *
     * @param zsys the value for cas_academician_foreign.zsys
     *
     * @mbggenerated
     */
    public void setZsys(String zsys) {
        this.zsys = zsys == null ? null : zsys.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_academician_foreign.xuebu
     *
     * @return the value of cas_academician_foreign.xuebu
     *
     * @mbggenerated
     */
    public String getXuebu() {
        return xuebu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_academician_foreign.xuebu
     *
     * @param xuebu the value for cas_academician_foreign.xuebu
     *
     * @mbggenerated
     */
    public void setXuebu(String xuebu) {
        this.xuebu = xuebu == null ? null : xuebu.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_academician_foreign.xingming
     *
     * @return the value of cas_academician_foreign.xingming
     *
     * @mbggenerated
     */
    public String getXingming() {
        return xingming;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_academician_foreign.xingming
     *
     * @param xingming the value for cas_academician_foreign.xingming
     *
     * @mbggenerated
     */
    public void setXingming(String xingming) {
        this.xingming = xingming == null ? null : xingming.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_academician_foreign.dxnf
     *
     * @return the value of cas_academician_foreign.dxnf
     *
     * @mbggenerated
     */
    public String getDxnf() {
        return dxnf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_academician_foreign.dxnf
     *
     * @param dxnf the value for cas_academician_foreign.dxnf
     *
     * @mbggenerated
     */
    public void setDxnf(String dxnf) {
        this.dxnf = dxnf == null ? null : dxnf.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_academician_foreign.xingbie
     *
     * @return the value of cas_academician_foreign.xingbie
     *
     * @mbggenerated
     */
    public String getXingbie() {
        return xingbie;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_academician_foreign.xingbie
     *
     * @param xingbie the value for cas_academician_foreign.xingbie
     *
     * @mbggenerated
     */
    public void setXingbie(String xingbie) {
        this.xingbie = xingbie == null ? null : xingbie.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_academician_foreign.guoji
     *
     * @return the value of cas_academician_foreign.guoji
     *
     * @mbggenerated
     */
    public String getGuoji() {
        return guoji;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_academician_foreign.guoji
     *
     * @param guoji the value for cas_academician_foreign.guoji
     *
     * @mbggenerated
     */
    public void setGuoji(String guoji) {
        this.guoji = guoji == null ? null : guoji.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_academician_foreign.csny
     *
     * @return the value of cas_academician_foreign.csny
     *
     * @mbggenerated
     */
    public String getCsny() {
        return csny;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_academician_foreign.csny
     *
     * @param csny the value for cas_academician_foreign.csny
     *
     * @mbggenerated
     */
    public void setCsny(String csny) {
        this.csny = csny == null ? null : csny.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_academician_foreign.nianling
     *
     * @return the value of cas_academician_foreign.nianling
     *
     * @mbggenerated
     */
    public String getNianling() {
        return nianling;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_academician_foreign.nianling
     *
     * @param nianling the value for cas_academician_foreign.nianling
     *
     * @mbggenerated
     */
    public void setNianling(String nianling) {
        this.nianling = nianling == null ? null : nianling.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_academician_foreign.qssj
     *
     * @return the value of cas_academician_foreign.qssj
     *
     * @mbggenerated
     */
    public String getQssj() {
        return qssj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_academician_foreign.qssj
     *
     * @param qssj the value for cas_academician_foreign.qssj
     *
     * @mbggenerated
     */
    public void setQssj(String qssj) {
        this.qssj = qssj == null ? null : qssj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_academician_foreign.chushengdi
     *
     * @return the value of cas_academician_foreign.chushengdi
     *
     * @mbggenerated
     */
    public String getChushengdi() {
        return chushengdi;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_academician_foreign.chushengdi
     *
     * @param chushengdi the value for cas_academician_foreign.chushengdi
     *
     * @mbggenerated
     */
    public void setChushengdi(String chushengdi) {
        this.chushengdi = chushengdi == null ? null : chushengdi.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_academician_foreign.byyx1
     *
     * @return the value of cas_academician_foreign.byyx1
     *
     * @mbggenerated
     */
    public String getByyx1() {
        return byyx1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_academician_foreign.byyx1
     *
     * @param byyx1 the value for cas_academician_foreign.byyx1
     *
     * @mbggenerated
     */
    public void setByyx1(String byyx1) {
        this.byyx1 = byyx1 == null ? null : byyx1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_academician_foreign.byyx2
     *
     * @return the value of cas_academician_foreign.byyx2
     *
     * @mbggenerated
     */
    public String getByyx2() {
        return byyx2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_academician_foreign.byyx2
     *
     * @param byyx2 the value for cas_academician_foreign.byyx2
     *
     * @mbggenerated
     */
    public void setByyx2(String byyx2) {
        this.byyx2 = byyx2 == null ? null : byyx2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_academician_foreign.byyx3
     *
     * @return the value of cas_academician_foreign.byyx3
     *
     * @mbggenerated
     */
    public String getByyx3() {
        return byyx3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_academician_foreign.byyx3
     *
     * @param byyx3 the value for cas_academician_foreign.byyx3
     *
     * @mbggenerated
     */
    public void setByyx3(String byyx3) {
        this.byyx3 = byyx3 == null ? null : byyx3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_academician_foreign.zhuanye
     *
     * @return the value of cas_academician_foreign.zhuanye
     *
     * @mbggenerated
     */
    public String getZhuanye() {
        return zhuanye;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_academician_foreign.zhuanye
     *
     * @param zhuanye the value for cas_academician_foreign.zhuanye
     *
     * @mbggenerated
     */
    public void setZhuanye(String zhuanye) {
        this.zhuanye = zhuanye == null ? null : zhuanye.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_academician_foreign.gzdw
     *
     * @return the value of cas_academician_foreign.gzdw
     *
     * @mbggenerated
     */
    public String getGzdw() {
        return gzdw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_academician_foreign.gzdw
     *
     * @param gzdw the value for cas_academician_foreign.gzdw
     *
     * @mbggenerated
     */
    public void setGzdw(String gzdw) {
        this.gzdw = gzdw == null ? null : gzdw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_academician_foreign.datasource_type
     *
     * @return the value of cas_academician_foreign.datasource_type
     *
     * @mbggenerated
     */
    public String getDatasourceType() {
        return datasourceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_academician_foreign.datasource_type
     *
     * @param datasourceType the value for cas_academician_foreign.datasource_type
     *
     * @mbggenerated
     */
    public void setDatasourceType(String datasourceType) {
        this.datasourceType = datasourceType == null ? null : datasourceType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_academician_foreign.etl_datasource
     *
     * @return the value of cas_academician_foreign.etl_datasource
     *
     * @mbggenerated
     */
    public String getEtlDatasource() {
        return etlDatasource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_academician_foreign.etl_datasource
     *
     * @param etlDatasource the value for cas_academician_foreign.etl_datasource
     *
     * @mbggenerated
     */
    public void setEtlDatasource(String etlDatasource) {
        this.etlDatasource = etlDatasource == null ? null : etlDatasource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_academician_foreign.firstinput_time
     *
     * @return the value of cas_academician_foreign.firstinput_time
     *
     * @mbggenerated
     */
    public Date getFirstinputTime() {
        return firstinputTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_academician_foreign.firstinput_time
     *
     * @param firstinputTime the value for cas_academician_foreign.firstinput_time
     *
     * @mbggenerated
     */
    public void setFirstinputTime(Date firstinputTime) {
        this.firstinputTime = firstinputTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_academician_foreign.laterupdate_time
     *
     * @return the value of cas_academician_foreign.laterupdate_time
     *
     * @mbggenerated
     */
    public Date getLaterupdateTime() {
        return laterupdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_academician_foreign.laterupdate_time
     *
     * @param laterupdateTime the value for cas_academician_foreign.laterupdate_time
     *
     * @mbggenerated
     */
    public void setLaterupdateTime(Date laterupdateTime) {
        this.laterupdateTime = laterupdateTime;
    }
}