package cn.arp.trend.entity.biz;

public class CasChinaAward10YearFinalWithBLOBs extends CasChinaAward10YearFinal {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_china_award_10year_final.main_wcr
     *
     * @mbggenerated
     */
    private String mainWcr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_china_award_10year_final.main_wcdw
     *
     * @mbggenerated
     */
    private String mainWcdw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_china_award_10year_final.other_main_wcr
     *
     * @mbggenerated
     */
    private String otherMainWcr;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_china_award_10year_final.main_wcr
     *
     * @return the value of cas_china_award_10year_final.main_wcr
     *
     * @mbggenerated
     */
    public String getMainWcr() {
        return mainWcr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_china_award_10year_final.main_wcr
     *
     * @param mainWcr the value for cas_china_award_10year_final.main_wcr
     *
     * @mbggenerated
     */
    public void setMainWcr(String mainWcr) {
        this.mainWcr = mainWcr == null ? null : mainWcr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_china_award_10year_final.main_wcdw
     *
     * @return the value of cas_china_award_10year_final.main_wcdw
     *
     * @mbggenerated
     */
    public String getMainWcdw() {
        return mainWcdw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_china_award_10year_final.main_wcdw
     *
     * @param mainWcdw the value for cas_china_award_10year_final.main_wcdw
     *
     * @mbggenerated
     */
    public void setMainWcdw(String mainWcdw) {
        this.mainWcdw = mainWcdw == null ? null : mainWcdw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_china_award_10year_final.other_main_wcr
     *
     * @return the value of cas_china_award_10year_final.other_main_wcr
     *
     * @mbggenerated
     */
    public String getOtherMainWcr() {
        return otherMainWcr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_china_award_10year_final.other_main_wcr
     *
     * @param otherMainWcr the value for cas_china_award_10year_final.other_main_wcr
     *
     * @mbggenerated
     */
    public void setOtherMainWcr(String otherMainWcr) {
        this.otherMainWcr = otherMainWcr == null ? null : otherMainWcr.trim();
    }
}