package cn.arp.trend.entity.biz;

import java.util.Date;

public class CasChinaAward10YearFinal {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_china_award_10year_final.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_china_award_10year_final.jxlb
     *
     * @mbggenerated
     */
    private String jxlb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_china_award_10year_final.hjnf
     *
     * @mbggenerated
     */
    private Double hjnf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_china_award_10year_final.hjdj
     *
     * @mbggenerated
     */
    private String hjdj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_china_award_10year_final.bh
     *
     * @mbggenerated
     */
    private String bh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_china_award_10year_final.xmmc_or_tdmc
     *
     * @mbggenerated
     */
    private String xmmcOrTdmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_china_award_10year_final.xmlb
     *
     * @mbggenerated
     */
    private String xmlb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_china_award_10year_final.first_wcr
     *
     * @mbggenerated
     */
    private String firstWcr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_china_award_10year_final.second_wcr
     *
     * @mbggenerated
     */
    private String secondWcr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_china_award_10year_final.third_wcr
     *
     * @mbggenerated
     */
    private String thirdWcr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_china_award_10year_final.first_wcdw_std
     *
     * @mbggenerated
     */
    private String firstWcdwStd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_china_award_10year_final.first_wcdw
     *
     * @mbggenerated
     */
    private String firstWcdw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_china_award_10year_final.second_wcdw_std
     *
     * @mbggenerated
     */
    private String secondWcdwStd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_china_award_10year_final.second_wcdw
     *
     * @mbggenerated
     */
    private String secondWcdw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_china_award_10year_final.third_wcdw_std
     *
     * @mbggenerated
     */
    private String thirdWcdwStd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_china_award_10year_final.third_wcdw
     *
     * @mbggenerated
     */
    private String thirdWcdw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_china_award_10year_final.other_main_wcdw_std
     *
     * @mbggenerated
     */
    private String otherMainWcdwStd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_china_award_10year_final.other_main_wcdw
     *
     * @mbggenerated
     */
    private String otherMainWcdw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_china_award_10year_final.tjdw_or_zj
     *
     * @mbggenerated
     */
    private String tjdwOrZj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_china_award_10year_final.remarks
     *
     * @mbggenerated
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_china_award_10year_final.datasource_type
     *
     * @mbggenerated
     */
    private String datasourceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_china_award_10year_final.etl_datasource
     *
     * @mbggenerated
     */
    private String etlDatasource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_china_award_10year_final.firstinput_time
     *
     * @mbggenerated
     */
    private Date firstinputTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_china_award_10year_final.laterupdate_time
     *
     * @mbggenerated
     */
    private Date laterupdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_china_award_10year_final.csrq
     *
     * @mbggenerated
     */
    private String csrq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_china_award_10year_final.qsrq
     *
     * @mbggenerated
     */
    private String qsrq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_china_award_10year_final.xb
     *
     * @mbggenerated
     */
    private String xb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_china_award_10year_final.ly
     *
     * @mbggenerated
     */
    private String ly;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_china_award_10year_final.id
     *
     * @return the value of cas_china_award_10year_final.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_china_award_10year_final.id
     *
     * @param id the value for cas_china_award_10year_final.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_china_award_10year_final.jxlb
     *
     * @return the value of cas_china_award_10year_final.jxlb
     *
     * @mbggenerated
     */
    public String getJxlb() {
        return jxlb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_china_award_10year_final.jxlb
     *
     * @param jxlb the value for cas_china_award_10year_final.jxlb
     *
     * @mbggenerated
     */
    public void setJxlb(String jxlb) {
        this.jxlb = jxlb == null ? null : jxlb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_china_award_10year_final.hjnf
     *
     * @return the value of cas_china_award_10year_final.hjnf
     *
     * @mbggenerated
     */
    public Double getHjnf() {
        return hjnf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_china_award_10year_final.hjnf
     *
     * @param hjnf the value for cas_china_award_10year_final.hjnf
     *
     * @mbggenerated
     */
    public void setHjnf(Double hjnf) {
        this.hjnf = hjnf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_china_award_10year_final.hjdj
     *
     * @return the value of cas_china_award_10year_final.hjdj
     *
     * @mbggenerated
     */
    public String getHjdj() {
        return hjdj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_china_award_10year_final.hjdj
     *
     * @param hjdj the value for cas_china_award_10year_final.hjdj
     *
     * @mbggenerated
     */
    public void setHjdj(String hjdj) {
        this.hjdj = hjdj == null ? null : hjdj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_china_award_10year_final.bh
     *
     * @return the value of cas_china_award_10year_final.bh
     *
     * @mbggenerated
     */
    public String getBh() {
        return bh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_china_award_10year_final.bh
     *
     * @param bh the value for cas_china_award_10year_final.bh
     *
     * @mbggenerated
     */
    public void setBh(String bh) {
        this.bh = bh == null ? null : bh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_china_award_10year_final.xmmc_or_tdmc
     *
     * @return the value of cas_china_award_10year_final.xmmc_or_tdmc
     *
     * @mbggenerated
     */
    public String getXmmcOrTdmc() {
        return xmmcOrTdmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_china_award_10year_final.xmmc_or_tdmc
     *
     * @param xmmcOrTdmc the value for cas_china_award_10year_final.xmmc_or_tdmc
     *
     * @mbggenerated
     */
    public void setXmmcOrTdmc(String xmmcOrTdmc) {
        this.xmmcOrTdmc = xmmcOrTdmc == null ? null : xmmcOrTdmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_china_award_10year_final.xmlb
     *
     * @return the value of cas_china_award_10year_final.xmlb
     *
     * @mbggenerated
     */
    public String getXmlb() {
        return xmlb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_china_award_10year_final.xmlb
     *
     * @param xmlb the value for cas_china_award_10year_final.xmlb
     *
     * @mbggenerated
     */
    public void setXmlb(String xmlb) {
        this.xmlb = xmlb == null ? null : xmlb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_china_award_10year_final.first_wcr
     *
     * @return the value of cas_china_award_10year_final.first_wcr
     *
     * @mbggenerated
     */
    public String getFirstWcr() {
        return firstWcr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_china_award_10year_final.first_wcr
     *
     * @param firstWcr the value for cas_china_award_10year_final.first_wcr
     *
     * @mbggenerated
     */
    public void setFirstWcr(String firstWcr) {
        this.firstWcr = firstWcr == null ? null : firstWcr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_china_award_10year_final.second_wcr
     *
     * @return the value of cas_china_award_10year_final.second_wcr
     *
     * @mbggenerated
     */
    public String getSecondWcr() {
        return secondWcr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_china_award_10year_final.second_wcr
     *
     * @param secondWcr the value for cas_china_award_10year_final.second_wcr
     *
     * @mbggenerated
     */
    public void setSecondWcr(String secondWcr) {
        this.secondWcr = secondWcr == null ? null : secondWcr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_china_award_10year_final.third_wcr
     *
     * @return the value of cas_china_award_10year_final.third_wcr
     *
     * @mbggenerated
     */
    public String getThirdWcr() {
        return thirdWcr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_china_award_10year_final.third_wcr
     *
     * @param thirdWcr the value for cas_china_award_10year_final.third_wcr
     *
     * @mbggenerated
     */
    public void setThirdWcr(String thirdWcr) {
        this.thirdWcr = thirdWcr == null ? null : thirdWcr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_china_award_10year_final.first_wcdw_std
     *
     * @return the value of cas_china_award_10year_final.first_wcdw_std
     *
     * @mbggenerated
     */
    public String getFirstWcdwStd() {
        return firstWcdwStd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_china_award_10year_final.first_wcdw_std
     *
     * @param firstWcdwStd the value for cas_china_award_10year_final.first_wcdw_std
     *
     * @mbggenerated
     */
    public void setFirstWcdwStd(String firstWcdwStd) {
        this.firstWcdwStd = firstWcdwStd == null ? null : firstWcdwStd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_china_award_10year_final.first_wcdw
     *
     * @return the value of cas_china_award_10year_final.first_wcdw
     *
     * @mbggenerated
     */
    public String getFirstWcdw() {
        return firstWcdw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_china_award_10year_final.first_wcdw
     *
     * @param firstWcdw the value for cas_china_award_10year_final.first_wcdw
     *
     * @mbggenerated
     */
    public void setFirstWcdw(String firstWcdw) {
        this.firstWcdw = firstWcdw == null ? null : firstWcdw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_china_award_10year_final.second_wcdw_std
     *
     * @return the value of cas_china_award_10year_final.second_wcdw_std
     *
     * @mbggenerated
     */
    public String getSecondWcdwStd() {
        return secondWcdwStd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_china_award_10year_final.second_wcdw_std
     *
     * @param secondWcdwStd the value for cas_china_award_10year_final.second_wcdw_std
     *
     * @mbggenerated
     */
    public void setSecondWcdwStd(String secondWcdwStd) {
        this.secondWcdwStd = secondWcdwStd == null ? null : secondWcdwStd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_china_award_10year_final.second_wcdw
     *
     * @return the value of cas_china_award_10year_final.second_wcdw
     *
     * @mbggenerated
     */
    public String getSecondWcdw() {
        return secondWcdw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_china_award_10year_final.second_wcdw
     *
     * @param secondWcdw the value for cas_china_award_10year_final.second_wcdw
     *
     * @mbggenerated
     */
    public void setSecondWcdw(String secondWcdw) {
        this.secondWcdw = secondWcdw == null ? null : secondWcdw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_china_award_10year_final.third_wcdw_std
     *
     * @return the value of cas_china_award_10year_final.third_wcdw_std
     *
     * @mbggenerated
     */
    public String getThirdWcdwStd() {
        return thirdWcdwStd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_china_award_10year_final.third_wcdw_std
     *
     * @param thirdWcdwStd the value for cas_china_award_10year_final.third_wcdw_std
     *
     * @mbggenerated
     */
    public void setThirdWcdwStd(String thirdWcdwStd) {
        this.thirdWcdwStd = thirdWcdwStd == null ? null : thirdWcdwStd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_china_award_10year_final.third_wcdw
     *
     * @return the value of cas_china_award_10year_final.third_wcdw
     *
     * @mbggenerated
     */
    public String getThirdWcdw() {
        return thirdWcdw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_china_award_10year_final.third_wcdw
     *
     * @param thirdWcdw the value for cas_china_award_10year_final.third_wcdw
     *
     * @mbggenerated
     */
    public void setThirdWcdw(String thirdWcdw) {
        this.thirdWcdw = thirdWcdw == null ? null : thirdWcdw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_china_award_10year_final.other_main_wcdw_std
     *
     * @return the value of cas_china_award_10year_final.other_main_wcdw_std
     *
     * @mbggenerated
     */
    public String getOtherMainWcdwStd() {
        return otherMainWcdwStd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_china_award_10year_final.other_main_wcdw_std
     *
     * @param otherMainWcdwStd the value for cas_china_award_10year_final.other_main_wcdw_std
     *
     * @mbggenerated
     */
    public void setOtherMainWcdwStd(String otherMainWcdwStd) {
        this.otherMainWcdwStd = otherMainWcdwStd == null ? null : otherMainWcdwStd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_china_award_10year_final.other_main_wcdw
     *
     * @return the value of cas_china_award_10year_final.other_main_wcdw
     *
     * @mbggenerated
     */
    public String getOtherMainWcdw() {
        return otherMainWcdw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_china_award_10year_final.other_main_wcdw
     *
     * @param otherMainWcdw the value for cas_china_award_10year_final.other_main_wcdw
     *
     * @mbggenerated
     */
    public void setOtherMainWcdw(String otherMainWcdw) {
        this.otherMainWcdw = otherMainWcdw == null ? null : otherMainWcdw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_china_award_10year_final.tjdw_or_zj
     *
     * @return the value of cas_china_award_10year_final.tjdw_or_zj
     *
     * @mbggenerated
     */
    public String getTjdwOrZj() {
        return tjdwOrZj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_china_award_10year_final.tjdw_or_zj
     *
     * @param tjdwOrZj the value for cas_china_award_10year_final.tjdw_or_zj
     *
     * @mbggenerated
     */
    public void setTjdwOrZj(String tjdwOrZj) {
        this.tjdwOrZj = tjdwOrZj == null ? null : tjdwOrZj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_china_award_10year_final.remarks
     *
     * @return the value of cas_china_award_10year_final.remarks
     *
     * @mbggenerated
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_china_award_10year_final.remarks
     *
     * @param remarks the value for cas_china_award_10year_final.remarks
     *
     * @mbggenerated
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks == null ? null : remarks.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_china_award_10year_final.datasource_type
     *
     * @return the value of cas_china_award_10year_final.datasource_type
     *
     * @mbggenerated
     */
    public String getDatasourceType() {
        return datasourceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_china_award_10year_final.datasource_type
     *
     * @param datasourceType the value for cas_china_award_10year_final.datasource_type
     *
     * @mbggenerated
     */
    public void setDatasourceType(String datasourceType) {
        this.datasourceType = datasourceType == null ? null : datasourceType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_china_award_10year_final.etl_datasource
     *
     * @return the value of cas_china_award_10year_final.etl_datasource
     *
     * @mbggenerated
     */
    public String getEtlDatasource() {
        return etlDatasource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_china_award_10year_final.etl_datasource
     *
     * @param etlDatasource the value for cas_china_award_10year_final.etl_datasource
     *
     * @mbggenerated
     */
    public void setEtlDatasource(String etlDatasource) {
        this.etlDatasource = etlDatasource == null ? null : etlDatasource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_china_award_10year_final.firstinput_time
     *
     * @return the value of cas_china_award_10year_final.firstinput_time
     *
     * @mbggenerated
     */
    public Date getFirstinputTime() {
        return firstinputTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_china_award_10year_final.firstinput_time
     *
     * @param firstinputTime the value for cas_china_award_10year_final.firstinput_time
     *
     * @mbggenerated
     */
    public void setFirstinputTime(Date firstinputTime) {
        this.firstinputTime = firstinputTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_china_award_10year_final.laterupdate_time
     *
     * @return the value of cas_china_award_10year_final.laterupdate_time
     *
     * @mbggenerated
     */
    public Date getLaterupdateTime() {
        return laterupdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_china_award_10year_final.laterupdate_time
     *
     * @param laterupdateTime the value for cas_china_award_10year_final.laterupdate_time
     *
     * @mbggenerated
     */
    public void setLaterupdateTime(Date laterupdateTime) {
        this.laterupdateTime = laterupdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_china_award_10year_final.csrq
     *
     * @return the value of cas_china_award_10year_final.csrq
     *
     * @mbggenerated
     */
    public String getCsrq() {
        return csrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_china_award_10year_final.csrq
     *
     * @param csrq the value for cas_china_award_10year_final.csrq
     *
     * @mbggenerated
     */
    public void setCsrq(String csrq) {
        this.csrq = csrq == null ? null : csrq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_china_award_10year_final.qsrq
     *
     * @return the value of cas_china_award_10year_final.qsrq
     *
     * @mbggenerated
     */
    public String getQsrq() {
        return qsrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_china_award_10year_final.qsrq
     *
     * @param qsrq the value for cas_china_award_10year_final.qsrq
     *
     * @mbggenerated
     */
    public void setQsrq(String qsrq) {
        this.qsrq = qsrq == null ? null : qsrq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_china_award_10year_final.xb
     *
     * @return the value of cas_china_award_10year_final.xb
     *
     * @mbggenerated
     */
    public String getXb() {
        return xb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_china_award_10year_final.xb
     *
     * @param xb the value for cas_china_award_10year_final.xb
     *
     * @mbggenerated
     */
    public void setXb(String xb) {
        this.xb = xb == null ? null : xb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_china_award_10year_final.ly
     *
     * @return the value of cas_china_award_10year_final.ly
     *
     * @mbggenerated
     */
    public String getLy() {
        return ly;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_china_award_10year_final.ly
     *
     * @param ly the value for cas_china_award_10year_final.ly
     *
     * @mbggenerated
     */
    public void setLy(String ly) {
        this.ly = ly == null ? null : ly.trim();
    }
}