package cn.arp.trend.entity.biz;

import java.util.Date;

public class CasEduFTeacherInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_edu_f_teacher_info.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_edu_f_teacher_info.staff_id
     *
     * @mbggenerated
     */
    private String staffId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_edu_f_teacher_info.id_no
     *
     * @mbggenerated
     */
    private String idNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_edu_f_teacher_info.birthday
     *
     * @mbggenerated
     */
    private String birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_edu_f_teacher_info.citizenship
     *
     * @mbggenerated
     */
    private Integer citizenship;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_edu_f_teacher_info.highest_degree
     *
     * @mbggenerated
     */
    private Integer highestDegree;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_edu_f_teacher_info.highest_edu
     *
     * @mbggenerated
     */
    private Integer highestEdu;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_edu_f_teacher_info.graduation_name
     *
     * @mbggenerated
     */
    private String graduationName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_edu_f_teacher_info.graduation_time
     *
     * @mbggenerated
     */
    private String graduationTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_edu_f_teacher_info.join_work_date
     *
     * @mbggenerated
     */
    private String joinWorkDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_edu_f_teacher_info.enroll_time
     *
     * @mbggenerated
     */
    private String enrollTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_edu_f_teacher_info.first_time_advisor
     *
     * @mbggenerated
     */
    private String firstTimeAdvisor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_edu_f_teacher_info.first_time_doctor
     *
     * @mbggenerated
     */
    private String firstTimeDoctor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_edu_f_teacher_info.subject_major
     *
     * @mbggenerated
     */
    private String subjectMajor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_edu_f_teacher_info.subject_one
     *
     * @mbggenerated
     */
    private String subjectOne;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_edu_f_teacher_info.Subject_major_one
     *
     * @mbggenerated
     */
    private String subjectMajorOne;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_edu_f_teacher_info.Subject_major_two
     *
     * @mbggenerated
     */
    private String subjectMajorTwo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_edu_f_teacher_info.Subject_major_three
     *
     * @mbggenerated
     */
    private String subjectMajorThree;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_edu_f_teacher_info.title_post
     *
     * @mbggenerated
     */
    private String titlePost;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_edu_f_teacher_info.Talent_type
     *
     * @mbggenerated
     */
    private String talentType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_edu_f_teacher_info.position
     *
     * @mbggenerated
     */
    private String position;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_edu_f_teacher_info.status
     *
     * @mbggenerated
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_edu_f_teacher_info.Mentor_code
     *
     * @mbggenerated
     */
    private String mentorCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_edu_f_teacher_info.Mentor_unit_name
     *
     * @mbggenerated
     */
    private String mentorUnitName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_edu_f_teacher_info.datasource_type
     *
     * @mbggenerated
     */
    private String datasourceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_edu_f_teacher_info.etl_datasource
     *
     * @mbggenerated
     */
    private String etlDatasource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_edu_f_teacher_info.firstinput_time
     *
     * @mbggenerated
     */
    private Date firstinputTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_edu_f_teacher_info.laterupdate_time
     *
     * @mbggenerated
     */
    private Date laterupdateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_edu_f_teacher_info.original_datasource_id
     *
     * @mbggenerated
     */
    private Integer originalDatasourceId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_edu_f_teacher_info.name
     *
     * @return the value of cas_edu_f_teacher_info.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_edu_f_teacher_info.name
     *
     * @param name the value for cas_edu_f_teacher_info.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_edu_f_teacher_info.staff_id
     *
     * @return the value of cas_edu_f_teacher_info.staff_id
     *
     * @mbggenerated
     */
    public String getStaffId() {
        return staffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_edu_f_teacher_info.staff_id
     *
     * @param staffId the value for cas_edu_f_teacher_info.staff_id
     *
     * @mbggenerated
     */
    public void setStaffId(String staffId) {
        this.staffId = staffId == null ? null : staffId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_edu_f_teacher_info.id_no
     *
     * @return the value of cas_edu_f_teacher_info.id_no
     *
     * @mbggenerated
     */
    public String getIdNo() {
        return idNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_edu_f_teacher_info.id_no
     *
     * @param idNo the value for cas_edu_f_teacher_info.id_no
     *
     * @mbggenerated
     */
    public void setIdNo(String idNo) {
        this.idNo = idNo == null ? null : idNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_edu_f_teacher_info.birthday
     *
     * @return the value of cas_edu_f_teacher_info.birthday
     *
     * @mbggenerated
     */
    public String getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_edu_f_teacher_info.birthday
     *
     * @param birthday the value for cas_edu_f_teacher_info.birthday
     *
     * @mbggenerated
     */
    public void setBirthday(String birthday) {
        this.birthday = birthday == null ? null : birthday.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_edu_f_teacher_info.citizenship
     *
     * @return the value of cas_edu_f_teacher_info.citizenship
     *
     * @mbggenerated
     */
    public Integer getCitizenship() {
        return citizenship;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_edu_f_teacher_info.citizenship
     *
     * @param citizenship the value for cas_edu_f_teacher_info.citizenship
     *
     * @mbggenerated
     */
    public void setCitizenship(Integer citizenship) {
        this.citizenship = citizenship;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_edu_f_teacher_info.highest_degree
     *
     * @return the value of cas_edu_f_teacher_info.highest_degree
     *
     * @mbggenerated
     */
    public Integer getHighestDegree() {
        return highestDegree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_edu_f_teacher_info.highest_degree
     *
     * @param highestDegree the value for cas_edu_f_teacher_info.highest_degree
     *
     * @mbggenerated
     */
    public void setHighestDegree(Integer highestDegree) {
        this.highestDegree = highestDegree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_edu_f_teacher_info.highest_edu
     *
     * @return the value of cas_edu_f_teacher_info.highest_edu
     *
     * @mbggenerated
     */
    public Integer getHighestEdu() {
        return highestEdu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_edu_f_teacher_info.highest_edu
     *
     * @param highestEdu the value for cas_edu_f_teacher_info.highest_edu
     *
     * @mbggenerated
     */
    public void setHighestEdu(Integer highestEdu) {
        this.highestEdu = highestEdu;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_edu_f_teacher_info.graduation_name
     *
     * @return the value of cas_edu_f_teacher_info.graduation_name
     *
     * @mbggenerated
     */
    public String getGraduationName() {
        return graduationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_edu_f_teacher_info.graduation_name
     *
     * @param graduationName the value for cas_edu_f_teacher_info.graduation_name
     *
     * @mbggenerated
     */
    public void setGraduationName(String graduationName) {
        this.graduationName = graduationName == null ? null : graduationName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_edu_f_teacher_info.graduation_time
     *
     * @return the value of cas_edu_f_teacher_info.graduation_time
     *
     * @mbggenerated
     */
    public String getGraduationTime() {
        return graduationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_edu_f_teacher_info.graduation_time
     *
     * @param graduationTime the value for cas_edu_f_teacher_info.graduation_time
     *
     * @mbggenerated
     */
    public void setGraduationTime(String graduationTime) {
        this.graduationTime = graduationTime == null ? null : graduationTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_edu_f_teacher_info.join_work_date
     *
     * @return the value of cas_edu_f_teacher_info.join_work_date
     *
     * @mbggenerated
     */
    public String getJoinWorkDate() {
        return joinWorkDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_edu_f_teacher_info.join_work_date
     *
     * @param joinWorkDate the value for cas_edu_f_teacher_info.join_work_date
     *
     * @mbggenerated
     */
    public void setJoinWorkDate(String joinWorkDate) {
        this.joinWorkDate = joinWorkDate == null ? null : joinWorkDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_edu_f_teacher_info.enroll_time
     *
     * @return the value of cas_edu_f_teacher_info.enroll_time
     *
     * @mbggenerated
     */
    public String getEnrollTime() {
        return enrollTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_edu_f_teacher_info.enroll_time
     *
     * @param enrollTime the value for cas_edu_f_teacher_info.enroll_time
     *
     * @mbggenerated
     */
    public void setEnrollTime(String enrollTime) {
        this.enrollTime = enrollTime == null ? null : enrollTime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_edu_f_teacher_info.first_time_advisor
     *
     * @return the value of cas_edu_f_teacher_info.first_time_advisor
     *
     * @mbggenerated
     */
    public String getFirstTimeAdvisor() {
        return firstTimeAdvisor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_edu_f_teacher_info.first_time_advisor
     *
     * @param firstTimeAdvisor the value for cas_edu_f_teacher_info.first_time_advisor
     *
     * @mbggenerated
     */
    public void setFirstTimeAdvisor(String firstTimeAdvisor) {
        this.firstTimeAdvisor = firstTimeAdvisor == null ? null : firstTimeAdvisor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_edu_f_teacher_info.first_time_doctor
     *
     * @return the value of cas_edu_f_teacher_info.first_time_doctor
     *
     * @mbggenerated
     */
    public String getFirstTimeDoctor() {
        return firstTimeDoctor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_edu_f_teacher_info.first_time_doctor
     *
     * @param firstTimeDoctor the value for cas_edu_f_teacher_info.first_time_doctor
     *
     * @mbggenerated
     */
    public void setFirstTimeDoctor(String firstTimeDoctor) {
        this.firstTimeDoctor = firstTimeDoctor == null ? null : firstTimeDoctor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_edu_f_teacher_info.subject_major
     *
     * @return the value of cas_edu_f_teacher_info.subject_major
     *
     * @mbggenerated
     */
    public String getSubjectMajor() {
        return subjectMajor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_edu_f_teacher_info.subject_major
     *
     * @param subjectMajor the value for cas_edu_f_teacher_info.subject_major
     *
     * @mbggenerated
     */
    public void setSubjectMajor(String subjectMajor) {
        this.subjectMajor = subjectMajor == null ? null : subjectMajor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_edu_f_teacher_info.subject_one
     *
     * @return the value of cas_edu_f_teacher_info.subject_one
     *
     * @mbggenerated
     */
    public String getSubjectOne() {
        return subjectOne;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_edu_f_teacher_info.subject_one
     *
     * @param subjectOne the value for cas_edu_f_teacher_info.subject_one
     *
     * @mbggenerated
     */
    public void setSubjectOne(String subjectOne) {
        this.subjectOne = subjectOne == null ? null : subjectOne.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_edu_f_teacher_info.Subject_major_one
     *
     * @return the value of cas_edu_f_teacher_info.Subject_major_one
     *
     * @mbggenerated
     */
    public String getSubjectMajorOne() {
        return subjectMajorOne;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_edu_f_teacher_info.Subject_major_one
     *
     * @param subjectMajorOne the value for cas_edu_f_teacher_info.Subject_major_one
     *
     * @mbggenerated
     */
    public void setSubjectMajorOne(String subjectMajorOne) {
        this.subjectMajorOne = subjectMajorOne == null ? null : subjectMajorOne.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_edu_f_teacher_info.Subject_major_two
     *
     * @return the value of cas_edu_f_teacher_info.Subject_major_two
     *
     * @mbggenerated
     */
    public String getSubjectMajorTwo() {
        return subjectMajorTwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_edu_f_teacher_info.Subject_major_two
     *
     * @param subjectMajorTwo the value for cas_edu_f_teacher_info.Subject_major_two
     *
     * @mbggenerated
     */
    public void setSubjectMajorTwo(String subjectMajorTwo) {
        this.subjectMajorTwo = subjectMajorTwo == null ? null : subjectMajorTwo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_edu_f_teacher_info.Subject_major_three
     *
     * @return the value of cas_edu_f_teacher_info.Subject_major_three
     *
     * @mbggenerated
     */
    public String getSubjectMajorThree() {
        return subjectMajorThree;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_edu_f_teacher_info.Subject_major_three
     *
     * @param subjectMajorThree the value for cas_edu_f_teacher_info.Subject_major_three
     *
     * @mbggenerated
     */
    public void setSubjectMajorThree(String subjectMajorThree) {
        this.subjectMajorThree = subjectMajorThree == null ? null : subjectMajorThree.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_edu_f_teacher_info.title_post
     *
     * @return the value of cas_edu_f_teacher_info.title_post
     *
     * @mbggenerated
     */
    public String getTitlePost() {
        return titlePost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_edu_f_teacher_info.title_post
     *
     * @param titlePost the value for cas_edu_f_teacher_info.title_post
     *
     * @mbggenerated
     */
    public void setTitlePost(String titlePost) {
        this.titlePost = titlePost == null ? null : titlePost.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_edu_f_teacher_info.Talent_type
     *
     * @return the value of cas_edu_f_teacher_info.Talent_type
     *
     * @mbggenerated
     */
    public String getTalentType() {
        return talentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_edu_f_teacher_info.Talent_type
     *
     * @param talentType the value for cas_edu_f_teacher_info.Talent_type
     *
     * @mbggenerated
     */
    public void setTalentType(String talentType) {
        this.talentType = talentType == null ? null : talentType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_edu_f_teacher_info.position
     *
     * @return the value of cas_edu_f_teacher_info.position
     *
     * @mbggenerated
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_edu_f_teacher_info.position
     *
     * @param position the value for cas_edu_f_teacher_info.position
     *
     * @mbggenerated
     */
    public void setPosition(String position) {
        this.position = position == null ? null : position.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_edu_f_teacher_info.status
     *
     * @return the value of cas_edu_f_teacher_info.status
     *
     * @mbggenerated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_edu_f_teacher_info.status
     *
     * @param status the value for cas_edu_f_teacher_info.status
     *
     * @mbggenerated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_edu_f_teacher_info.Mentor_code
     *
     * @return the value of cas_edu_f_teacher_info.Mentor_code
     *
     * @mbggenerated
     */
    public String getMentorCode() {
        return mentorCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_edu_f_teacher_info.Mentor_code
     *
     * @param mentorCode the value for cas_edu_f_teacher_info.Mentor_code
     *
     * @mbggenerated
     */
    public void setMentorCode(String mentorCode) {
        this.mentorCode = mentorCode == null ? null : mentorCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_edu_f_teacher_info.Mentor_unit_name
     *
     * @return the value of cas_edu_f_teacher_info.Mentor_unit_name
     *
     * @mbggenerated
     */
    public String getMentorUnitName() {
        return mentorUnitName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_edu_f_teacher_info.Mentor_unit_name
     *
     * @param mentorUnitName the value for cas_edu_f_teacher_info.Mentor_unit_name
     *
     * @mbggenerated
     */
    public void setMentorUnitName(String mentorUnitName) {
        this.mentorUnitName = mentorUnitName == null ? null : mentorUnitName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_edu_f_teacher_info.datasource_type
     *
     * @return the value of cas_edu_f_teacher_info.datasource_type
     *
     * @mbggenerated
     */
    public String getDatasourceType() {
        return datasourceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_edu_f_teacher_info.datasource_type
     *
     * @param datasourceType the value for cas_edu_f_teacher_info.datasource_type
     *
     * @mbggenerated
     */
    public void setDatasourceType(String datasourceType) {
        this.datasourceType = datasourceType == null ? null : datasourceType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_edu_f_teacher_info.etl_datasource
     *
     * @return the value of cas_edu_f_teacher_info.etl_datasource
     *
     * @mbggenerated
     */
    public String getEtlDatasource() {
        return etlDatasource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_edu_f_teacher_info.etl_datasource
     *
     * @param etlDatasource the value for cas_edu_f_teacher_info.etl_datasource
     *
     * @mbggenerated
     */
    public void setEtlDatasource(String etlDatasource) {
        this.etlDatasource = etlDatasource == null ? null : etlDatasource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_edu_f_teacher_info.firstinput_time
     *
     * @return the value of cas_edu_f_teacher_info.firstinput_time
     *
     * @mbggenerated
     */
    public Date getFirstinputTime() {
        return firstinputTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_edu_f_teacher_info.firstinput_time
     *
     * @param firstinputTime the value for cas_edu_f_teacher_info.firstinput_time
     *
     * @mbggenerated
     */
    public void setFirstinputTime(Date firstinputTime) {
        this.firstinputTime = firstinputTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_edu_f_teacher_info.laterupdate_time
     *
     * @return the value of cas_edu_f_teacher_info.laterupdate_time
     *
     * @mbggenerated
     */
    public Date getLaterupdateTime() {
        return laterupdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_edu_f_teacher_info.laterupdate_time
     *
     * @param laterupdateTime the value for cas_edu_f_teacher_info.laterupdate_time
     *
     * @mbggenerated
     */
    public void setLaterupdateTime(Date laterupdateTime) {
        this.laterupdateTime = laterupdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_edu_f_teacher_info.original_datasource_id
     *
     * @return the value of cas_edu_f_teacher_info.original_datasource_id
     *
     * @mbggenerated
     */
    public Integer getOriginalDatasourceId() {
        return originalDatasourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_edu_f_teacher_info.original_datasource_id
     *
     * @param originalDatasourceId the value for cas_edu_f_teacher_info.original_datasource_id
     *
     * @mbggenerated
     */
    public void setOriginalDatasourceId(Integer originalDatasourceId) {
        this.originalDatasourceId = originalDatasourceId;
    }
}