package cn.arp.trend.entity.biz;

import java.util.Date;

public class CasHlhlAwardWinner {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_hlhl_award_winner.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_hlhl_award_winner.desc
     *
     * @mbggenerated
     */
    private String desc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_hlhl_award_winner.pid
     *
     * @mbggenerated
     */
    private Long pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_hlhl_award_winner.cid
     *
     * @mbggenerated
     */
    private Long cid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_hlhl_award_winner.metaid
     *
     * @mbggenerated
     */
    private Long metaid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_hlhl_award_winner.xm
     *
     * @mbggenerated
     */
    private String xm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_hlhl_award_winner.xb
     *
     * @mbggenerated
     */
    private String xb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_hlhl_award_winner.nl
     *
     * @mbggenerated
     */
    private String nl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_hlhl_award_winner.nd
     *
     * @mbggenerated
     */
    private String nd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_hlhl_award_winner.hjjx
     *
     * @mbggenerated
     */
    private String hjjx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_hlhl_award_winner.hjxk
     *
     * @mbggenerated
     */
    private String hjxk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_hlhl_award_winner.gzdw_std
     *
     * @mbggenerated
     */
    private String gzdwStd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_hlhl_award_winner.gzdw
     *
     * @mbggenerated
     */
    private String gzdw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_hlhl_award_winner.ysqk
     *
     * @mbggenerated
     */
    private String ysqk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_hlhl_award_winner.datasource_type
     *
     * @mbggenerated
     */
    private String datasourceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_hlhl_award_winner.etl_datasource
     *
     * @mbggenerated
     */
    private String etlDatasource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_hlhl_award_winner.firstinput_time
     *
     * @mbggenerated
     */
    private Date firstinputTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_hlhl_award_winner.laterupdate_time
     *
     * @mbggenerated
     */
    private Date laterupdateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_hlhl_award_winner.id
     *
     * @return the value of cas_hlhl_award_winner.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_hlhl_award_winner.id
     *
     * @param id the value for cas_hlhl_award_winner.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_hlhl_award_winner.desc
     *
     * @return the value of cas_hlhl_award_winner.desc
     *
     * @mbggenerated
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_hlhl_award_winner.desc
     *
     * @param desc the value for cas_hlhl_award_winner.desc
     *
     * @mbggenerated
     */
    public void setDesc(String desc) {
        this.desc = desc == null ? null : desc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_hlhl_award_winner.pid
     *
     * @return the value of cas_hlhl_award_winner.pid
     *
     * @mbggenerated
     */
    public Long getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_hlhl_award_winner.pid
     *
     * @param pid the value for cas_hlhl_award_winner.pid
     *
     * @mbggenerated
     */
    public void setPid(Long pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_hlhl_award_winner.cid
     *
     * @return the value of cas_hlhl_award_winner.cid
     *
     * @mbggenerated
     */
    public Long getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_hlhl_award_winner.cid
     *
     * @param cid the value for cas_hlhl_award_winner.cid
     *
     * @mbggenerated
     */
    public void setCid(Long cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_hlhl_award_winner.metaid
     *
     * @return the value of cas_hlhl_award_winner.metaid
     *
     * @mbggenerated
     */
    public Long getMetaid() {
        return metaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_hlhl_award_winner.metaid
     *
     * @param metaid the value for cas_hlhl_award_winner.metaid
     *
     * @mbggenerated
     */
    public void setMetaid(Long metaid) {
        this.metaid = metaid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_hlhl_award_winner.xm
     *
     * @return the value of cas_hlhl_award_winner.xm
     *
     * @mbggenerated
     */
    public String getXm() {
        return xm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_hlhl_award_winner.xm
     *
     * @param xm the value for cas_hlhl_award_winner.xm
     *
     * @mbggenerated
     */
    public void setXm(String xm) {
        this.xm = xm == null ? null : xm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_hlhl_award_winner.xb
     *
     * @return the value of cas_hlhl_award_winner.xb
     *
     * @mbggenerated
     */
    public String getXb() {
        return xb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_hlhl_award_winner.xb
     *
     * @param xb the value for cas_hlhl_award_winner.xb
     *
     * @mbggenerated
     */
    public void setXb(String xb) {
        this.xb = xb == null ? null : xb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_hlhl_award_winner.nl
     *
     * @return the value of cas_hlhl_award_winner.nl
     *
     * @mbggenerated
     */
    public String getNl() {
        return nl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_hlhl_award_winner.nl
     *
     * @param nl the value for cas_hlhl_award_winner.nl
     *
     * @mbggenerated
     */
    public void setNl(String nl) {
        this.nl = nl == null ? null : nl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_hlhl_award_winner.nd
     *
     * @return the value of cas_hlhl_award_winner.nd
     *
     * @mbggenerated
     */
    public String getNd() {
        return nd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_hlhl_award_winner.nd
     *
     * @param nd the value for cas_hlhl_award_winner.nd
     *
     * @mbggenerated
     */
    public void setNd(String nd) {
        this.nd = nd == null ? null : nd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_hlhl_award_winner.hjjx
     *
     * @return the value of cas_hlhl_award_winner.hjjx
     *
     * @mbggenerated
     */
    public String getHjjx() {
        return hjjx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_hlhl_award_winner.hjjx
     *
     * @param hjjx the value for cas_hlhl_award_winner.hjjx
     *
     * @mbggenerated
     */
    public void setHjjx(String hjjx) {
        this.hjjx = hjjx == null ? null : hjjx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_hlhl_award_winner.hjxk
     *
     * @return the value of cas_hlhl_award_winner.hjxk
     *
     * @mbggenerated
     */
    public String getHjxk() {
        return hjxk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_hlhl_award_winner.hjxk
     *
     * @param hjxk the value for cas_hlhl_award_winner.hjxk
     *
     * @mbggenerated
     */
    public void setHjxk(String hjxk) {
        this.hjxk = hjxk == null ? null : hjxk.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_hlhl_award_winner.gzdw_std
     *
     * @return the value of cas_hlhl_award_winner.gzdw_std
     *
     * @mbggenerated
     */
    public String getGzdwStd() {
        return gzdwStd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_hlhl_award_winner.gzdw_std
     *
     * @param gzdwStd the value for cas_hlhl_award_winner.gzdw_std
     *
     * @mbggenerated
     */
    public void setGzdwStd(String gzdwStd) {
        this.gzdwStd = gzdwStd == null ? null : gzdwStd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_hlhl_award_winner.gzdw
     *
     * @return the value of cas_hlhl_award_winner.gzdw
     *
     * @mbggenerated
     */
    public String getGzdw() {
        return gzdw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_hlhl_award_winner.gzdw
     *
     * @param gzdw the value for cas_hlhl_award_winner.gzdw
     *
     * @mbggenerated
     */
    public void setGzdw(String gzdw) {
        this.gzdw = gzdw == null ? null : gzdw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_hlhl_award_winner.ysqk
     *
     * @return the value of cas_hlhl_award_winner.ysqk
     *
     * @mbggenerated
     */
    public String getYsqk() {
        return ysqk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_hlhl_award_winner.ysqk
     *
     * @param ysqk the value for cas_hlhl_award_winner.ysqk
     *
     * @mbggenerated
     */
    public void setYsqk(String ysqk) {
        this.ysqk = ysqk == null ? null : ysqk.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_hlhl_award_winner.datasource_type
     *
     * @return the value of cas_hlhl_award_winner.datasource_type
     *
     * @mbggenerated
     */
    public String getDatasourceType() {
        return datasourceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_hlhl_award_winner.datasource_type
     *
     * @param datasourceType the value for cas_hlhl_award_winner.datasource_type
     *
     * @mbggenerated
     */
    public void setDatasourceType(String datasourceType) {
        this.datasourceType = datasourceType == null ? null : datasourceType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_hlhl_award_winner.etl_datasource
     *
     * @return the value of cas_hlhl_award_winner.etl_datasource
     *
     * @mbggenerated
     */
    public String getEtlDatasource() {
        return etlDatasource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_hlhl_award_winner.etl_datasource
     *
     * @param etlDatasource the value for cas_hlhl_award_winner.etl_datasource
     *
     * @mbggenerated
     */
    public void setEtlDatasource(String etlDatasource) {
        this.etlDatasource = etlDatasource == null ? null : etlDatasource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_hlhl_award_winner.firstinput_time
     *
     * @return the value of cas_hlhl_award_winner.firstinput_time
     *
     * @mbggenerated
     */
    public Date getFirstinputTime() {
        return firstinputTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_hlhl_award_winner.firstinput_time
     *
     * @param firstinputTime the value for cas_hlhl_award_winner.firstinput_time
     *
     * @mbggenerated
     */
    public void setFirstinputTime(Date firstinputTime) {
        this.firstinputTime = firstinputTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_hlhl_award_winner.laterupdate_time
     *
     * @return the value of cas_hlhl_award_winner.laterupdate_time
     *
     * @mbggenerated
     */
    public Date getLaterupdateTime() {
        return laterupdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_hlhl_award_winner.laterupdate_time
     *
     * @param laterupdateTime the value for cas_hlhl_award_winner.laterupdate_time
     *
     * @mbggenerated
     */
    public void setLaterupdateTime(Date laterupdateTime) {
        this.laterupdateTime = laterupdateTime;
    }
}