package cn.arp.trend.entity.biz;

import java.util.Date;

public class CasInstitutionIncome {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_institution_income.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_institution_income.desc
     *
     * @mbggenerated
     */
    private String desc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_institution_income.stat_standard
     *
     * @mbggenerated
     */
    private String statStandard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_institution_income.stat_year
     *
     * @mbggenerated
     */
    private String statYear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_institution_income.jgmc
     *
     * @mbggenerated
     */
    private String jgmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_institution_income.sydwzsr
     *
     * @mbggenerated
     */
    private Long sydwzsr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_institution_income.czbtsr
     *
     * @mbggenerated
     */
    private Long czbtsr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_institution_income.zsrbrzk
     *
     * @mbggenerated
     */
    private Long zsrbrzk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_institution_income.sysr
     *
     * @mbggenerated
     */
    private Long sysr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_institution_income.kysr
     *
     * @mbggenerated
     */
    private Long kysr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_institution_income.jssr
     *
     * @mbggenerated
     */
    private Long jssr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_institution_income.szcpsr
     *
     * @mbggenerated
     */
    private Long szcpsr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_institution_income.yswzjsr
     *
     * @mbggenerated
     */
    private Long yswzjsr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_institution_income.jysr
     *
     * @mbggenerated
     */
    private Long jysr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_institution_income.qtsr
     *
     * @mbggenerated
     */
    private Long qtsr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_institution_income.datasource_type
     *
     * @mbggenerated
     */
    private String datasourceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_institution_income.etl_datasource
     *
     * @mbggenerated
     */
    private String etlDatasource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_institution_income.firstinput_time
     *
     * @mbggenerated
     */
    private Date firstinputTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_institution_income.laterupdate_time
     *
     * @mbggenerated
     */
    private Date laterupdateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_institution_income.id
     *
     * @return the value of cas_institution_income.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_institution_income.id
     *
     * @param id the value for cas_institution_income.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_institution_income.desc
     *
     * @return the value of cas_institution_income.desc
     *
     * @mbggenerated
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_institution_income.desc
     *
     * @param desc the value for cas_institution_income.desc
     *
     * @mbggenerated
     */
    public void setDesc(String desc) {
        this.desc = desc == null ? null : desc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_institution_income.stat_standard
     *
     * @return the value of cas_institution_income.stat_standard
     *
     * @mbggenerated
     */
    public String getStatStandard() {
        return statStandard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_institution_income.stat_standard
     *
     * @param statStandard the value for cas_institution_income.stat_standard
     *
     * @mbggenerated
     */
    public void setStatStandard(String statStandard) {
        this.statStandard = statStandard == null ? null : statStandard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_institution_income.stat_year
     *
     * @return the value of cas_institution_income.stat_year
     *
     * @mbggenerated
     */
    public String getStatYear() {
        return statYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_institution_income.stat_year
     *
     * @param statYear the value for cas_institution_income.stat_year
     *
     * @mbggenerated
     */
    public void setStatYear(String statYear) {
        this.statYear = statYear == null ? null : statYear.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_institution_income.jgmc
     *
     * @return the value of cas_institution_income.jgmc
     *
     * @mbggenerated
     */
    public String getJgmc() {
        return jgmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_institution_income.jgmc
     *
     * @param jgmc the value for cas_institution_income.jgmc
     *
     * @mbggenerated
     */
    public void setJgmc(String jgmc) {
        this.jgmc = jgmc == null ? null : jgmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_institution_income.sydwzsr
     *
     * @return the value of cas_institution_income.sydwzsr
     *
     * @mbggenerated
     */
    public Long getSydwzsr() {
        return sydwzsr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_institution_income.sydwzsr
     *
     * @param sydwzsr the value for cas_institution_income.sydwzsr
     *
     * @mbggenerated
     */
    public void setSydwzsr(Long sydwzsr) {
        this.sydwzsr = sydwzsr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_institution_income.czbtsr
     *
     * @return the value of cas_institution_income.czbtsr
     *
     * @mbggenerated
     */
    public Long getCzbtsr() {
        return czbtsr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_institution_income.czbtsr
     *
     * @param czbtsr the value for cas_institution_income.czbtsr
     *
     * @mbggenerated
     */
    public void setCzbtsr(Long czbtsr) {
        this.czbtsr = czbtsr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_institution_income.zsrbrzk
     *
     * @return the value of cas_institution_income.zsrbrzk
     *
     * @mbggenerated
     */
    public Long getZsrbrzk() {
        return zsrbrzk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_institution_income.zsrbrzk
     *
     * @param zsrbrzk the value for cas_institution_income.zsrbrzk
     *
     * @mbggenerated
     */
    public void setZsrbrzk(Long zsrbrzk) {
        this.zsrbrzk = zsrbrzk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_institution_income.sysr
     *
     * @return the value of cas_institution_income.sysr
     *
     * @mbggenerated
     */
    public Long getSysr() {
        return sysr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_institution_income.sysr
     *
     * @param sysr the value for cas_institution_income.sysr
     *
     * @mbggenerated
     */
    public void setSysr(Long sysr) {
        this.sysr = sysr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_institution_income.kysr
     *
     * @return the value of cas_institution_income.kysr
     *
     * @mbggenerated
     */
    public Long getKysr() {
        return kysr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_institution_income.kysr
     *
     * @param kysr the value for cas_institution_income.kysr
     *
     * @mbggenerated
     */
    public void setKysr(Long kysr) {
        this.kysr = kysr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_institution_income.jssr
     *
     * @return the value of cas_institution_income.jssr
     *
     * @mbggenerated
     */
    public Long getJssr() {
        return jssr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_institution_income.jssr
     *
     * @param jssr the value for cas_institution_income.jssr
     *
     * @mbggenerated
     */
    public void setJssr(Long jssr) {
        this.jssr = jssr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_institution_income.szcpsr
     *
     * @return the value of cas_institution_income.szcpsr
     *
     * @mbggenerated
     */
    public Long getSzcpsr() {
        return szcpsr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_institution_income.szcpsr
     *
     * @param szcpsr the value for cas_institution_income.szcpsr
     *
     * @mbggenerated
     */
    public void setSzcpsr(Long szcpsr) {
        this.szcpsr = szcpsr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_institution_income.yswzjsr
     *
     * @return the value of cas_institution_income.yswzjsr
     *
     * @mbggenerated
     */
    public Long getYswzjsr() {
        return yswzjsr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_institution_income.yswzjsr
     *
     * @param yswzjsr the value for cas_institution_income.yswzjsr
     *
     * @mbggenerated
     */
    public void setYswzjsr(Long yswzjsr) {
        this.yswzjsr = yswzjsr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_institution_income.jysr
     *
     * @return the value of cas_institution_income.jysr
     *
     * @mbggenerated
     */
    public Long getJysr() {
        return jysr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_institution_income.jysr
     *
     * @param jysr the value for cas_institution_income.jysr
     *
     * @mbggenerated
     */
    public void setJysr(Long jysr) {
        this.jysr = jysr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_institution_income.qtsr
     *
     * @return the value of cas_institution_income.qtsr
     *
     * @mbggenerated
     */
    public Long getQtsr() {
        return qtsr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_institution_income.qtsr
     *
     * @param qtsr the value for cas_institution_income.qtsr
     *
     * @mbggenerated
     */
    public void setQtsr(Long qtsr) {
        this.qtsr = qtsr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_institution_income.datasource_type
     *
     * @return the value of cas_institution_income.datasource_type
     *
     * @mbggenerated
     */
    public String getDatasourceType() {
        return datasourceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_institution_income.datasource_type
     *
     * @param datasourceType the value for cas_institution_income.datasource_type
     *
     * @mbggenerated
     */
    public void setDatasourceType(String datasourceType) {
        this.datasourceType = datasourceType == null ? null : datasourceType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_institution_income.etl_datasource
     *
     * @return the value of cas_institution_income.etl_datasource
     *
     * @mbggenerated
     */
    public String getEtlDatasource() {
        return etlDatasource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_institution_income.etl_datasource
     *
     * @param etlDatasource the value for cas_institution_income.etl_datasource
     *
     * @mbggenerated
     */
    public void setEtlDatasource(String etlDatasource) {
        this.etlDatasource = etlDatasource == null ? null : etlDatasource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_institution_income.firstinput_time
     *
     * @return the value of cas_institution_income.firstinput_time
     *
     * @mbggenerated
     */
    public Date getFirstinputTime() {
        return firstinputTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_institution_income.firstinput_time
     *
     * @param firstinputTime the value for cas_institution_income.firstinput_time
     *
     * @mbggenerated
     */
    public void setFirstinputTime(Date firstinputTime) {
        this.firstinputTime = firstinputTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_institution_income.laterupdate_time
     *
     * @return the value of cas_institution_income.laterupdate_time
     *
     * @mbggenerated
     */
    public Date getLaterupdateTime() {
        return laterupdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_institution_income.laterupdate_time
     *
     * @param laterupdateTime the value for cas_institution_income.laterupdate_time
     *
     * @mbggenerated
     */
    public void setLaterupdateTime(Date laterupdateTime) {
        this.laterupdateTime = laterupdateTime;
    }
}