package cn.arp.trend.entity.biz;

import java.util.Date;

public class CasNo1IrcPm14 {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_no1_irc_pm_14.JGBH
     *
     * @mbggenerated
     */
    private String jgbh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_no1_irc_pm_14.YEAR
     *
     * @mbggenerated
     */
    private String year;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_no1_irc_pm_14.SRJE
     *
     * @mbggenerated
     */
    private Double srje;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_no1_irc_pm_14.ZGZS
     *
     * @mbggenerated
     */
    private Double zgzs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_no1_irc_pm_14.etl_datasource
     *
     * @mbggenerated
     */
    private String etlDatasource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_no1_irc_pm_14.datasource_type
     *
     * @mbggenerated
     */
    private String datasourceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_no1_irc_pm_14.firstinput_time
     *
     * @mbggenerated
     */
    private Date firstinputTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_no1_irc_pm_14.laterupdate_time
     *
     * @mbggenerated
     */
    private Date laterupdateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_no1_irc_pm_14.JGBH
     *
     * @return the value of cas_no1_irc_pm_14.JGBH
     *
     * @mbggenerated
     */
    public String getJgbh() {
        return jgbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_no1_irc_pm_14.JGBH
     *
     * @param jgbh the value for cas_no1_irc_pm_14.JGBH
     *
     * @mbggenerated
     */
    public void setJgbh(String jgbh) {
        this.jgbh = jgbh == null ? null : jgbh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_no1_irc_pm_14.YEAR
     *
     * @return the value of cas_no1_irc_pm_14.YEAR
     *
     * @mbggenerated
     */
    public String getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_no1_irc_pm_14.YEAR
     *
     * @param year the value for cas_no1_irc_pm_14.YEAR
     *
     * @mbggenerated
     */
    public void setYear(String year) {
        this.year = year == null ? null : year.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_no1_irc_pm_14.SRJE
     *
     * @return the value of cas_no1_irc_pm_14.SRJE
     *
     * @mbggenerated
     */
    public Double getSrje() {
        return srje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_no1_irc_pm_14.SRJE
     *
     * @param srje the value for cas_no1_irc_pm_14.SRJE
     *
     * @mbggenerated
     */
    public void setSrje(Double srje) {
        this.srje = srje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_no1_irc_pm_14.ZGZS
     *
     * @return the value of cas_no1_irc_pm_14.ZGZS
     *
     * @mbggenerated
     */
    public Double getZgzs() {
        return zgzs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_no1_irc_pm_14.ZGZS
     *
     * @param zgzs the value for cas_no1_irc_pm_14.ZGZS
     *
     * @mbggenerated
     */
    public void setZgzs(Double zgzs) {
        this.zgzs = zgzs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_no1_irc_pm_14.etl_datasource
     *
     * @return the value of cas_no1_irc_pm_14.etl_datasource
     *
     * @mbggenerated
     */
    public String getEtlDatasource() {
        return etlDatasource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_no1_irc_pm_14.etl_datasource
     *
     * @param etlDatasource the value for cas_no1_irc_pm_14.etl_datasource
     *
     * @mbggenerated
     */
    public void setEtlDatasource(String etlDatasource) {
        this.etlDatasource = etlDatasource == null ? null : etlDatasource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_no1_irc_pm_14.datasource_type
     *
     * @return the value of cas_no1_irc_pm_14.datasource_type
     *
     * @mbggenerated
     */
    public String getDatasourceType() {
        return datasourceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_no1_irc_pm_14.datasource_type
     *
     * @param datasourceType the value for cas_no1_irc_pm_14.datasource_type
     *
     * @mbggenerated
     */
    public void setDatasourceType(String datasourceType) {
        this.datasourceType = datasourceType == null ? null : datasourceType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_no1_irc_pm_14.firstinput_time
     *
     * @return the value of cas_no1_irc_pm_14.firstinput_time
     *
     * @mbggenerated
     */
    public Date getFirstinputTime() {
        return firstinputTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_no1_irc_pm_14.firstinput_time
     *
     * @param firstinputTime the value for cas_no1_irc_pm_14.firstinput_time
     *
     * @mbggenerated
     */
    public void setFirstinputTime(Date firstinputTime) {
        this.firstinputTime = firstinputTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_no1_irc_pm_14.laterupdate_time
     *
     * @return the value of cas_no1_irc_pm_14.laterupdate_time
     *
     * @mbggenerated
     */
    public Date getLaterupdateTime() {
        return laterupdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_no1_irc_pm_14.laterupdate_time
     *
     * @param laterupdateTime the value for cas_no1_irc_pm_14.laterupdate_time
     *
     * @mbggenerated
     */
    public void setLaterupdateTime(Date laterupdateTime) {
        this.laterupdateTime = laterupdateTime;
    }
}