package cn.arp.trend.entity.biz;

import java.util.Date;

public class CasPxxJcptCdsysXwPxLwKxjFmjJbj {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_pxx_jcpt_cdsys_xw_px_lw_kxj_fmj_jbj.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_pxx_jcpt_cdsys_xw_px_lw_kxj_fmj_jbj.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_pxx_jcpt_cdsys_xw_px_lw_kxj_fmj_jbj.date
     *
     * @mbggenerated
     */
    private String date;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_pxx_jcpt_cdsys_xw_px_lw_kxj_fmj_jbj.count
     *
     * @mbggenerated
     */
    private Double count;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_pxx_jcpt_cdsys_xw_px_lw_kxj_fmj_jbj.firstinput_time
     *
     * @mbggenerated
     */
    private Date firstinputTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_pxx_jcpt_cdsys_xw_px_lw_kxj_fmj_jbj.type
     *
     * @mbggenerated
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_pxx_jcpt_cdsys_xw_px_lw_kxj_fmj_jbj.datasource_type
     *
     * @mbggenerated
     */
    private String datasourceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_pxx_jcpt_cdsys_xw_px_lw_kxj_fmj_jbj.etl_datasource
     *
     * @mbggenerated
     */
    private String etlDatasource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_pxx_jcpt_cdsys_xw_px_lw_kxj_fmj_jbj.laterupdate_time
     *
     * @mbggenerated
     */
    private Date laterupdateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_pxx_jcpt_cdsys_xw_px_lw_kxj_fmj_jbj.id
     *
     * @return the value of cas_pxx_jcpt_cdsys_xw_px_lw_kxj_fmj_jbj.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_pxx_jcpt_cdsys_xw_px_lw_kxj_fmj_jbj.id
     *
     * @param id the value for cas_pxx_jcpt_cdsys_xw_px_lw_kxj_fmj_jbj.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_pxx_jcpt_cdsys_xw_px_lw_kxj_fmj_jbj.name
     *
     * @return the value of cas_pxx_jcpt_cdsys_xw_px_lw_kxj_fmj_jbj.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_pxx_jcpt_cdsys_xw_px_lw_kxj_fmj_jbj.name
     *
     * @param name the value for cas_pxx_jcpt_cdsys_xw_px_lw_kxj_fmj_jbj.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_pxx_jcpt_cdsys_xw_px_lw_kxj_fmj_jbj.date
     *
     * @return the value of cas_pxx_jcpt_cdsys_xw_px_lw_kxj_fmj_jbj.date
     *
     * @mbggenerated
     */
    public String getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_pxx_jcpt_cdsys_xw_px_lw_kxj_fmj_jbj.date
     *
     * @param date the value for cas_pxx_jcpt_cdsys_xw_px_lw_kxj_fmj_jbj.date
     *
     * @mbggenerated
     */
    public void setDate(String date) {
        this.date = date == null ? null : date.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_pxx_jcpt_cdsys_xw_px_lw_kxj_fmj_jbj.count
     *
     * @return the value of cas_pxx_jcpt_cdsys_xw_px_lw_kxj_fmj_jbj.count
     *
     * @mbggenerated
     */
    public Double getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_pxx_jcpt_cdsys_xw_px_lw_kxj_fmj_jbj.count
     *
     * @param count the value for cas_pxx_jcpt_cdsys_xw_px_lw_kxj_fmj_jbj.count
     *
     * @mbggenerated
     */
    public void setCount(Double count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_pxx_jcpt_cdsys_xw_px_lw_kxj_fmj_jbj.firstinput_time
     *
     * @return the value of cas_pxx_jcpt_cdsys_xw_px_lw_kxj_fmj_jbj.firstinput_time
     *
     * @mbggenerated
     */
    public Date getFirstinputTime() {
        return firstinputTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_pxx_jcpt_cdsys_xw_px_lw_kxj_fmj_jbj.firstinput_time
     *
     * @param firstinputTime the value for cas_pxx_jcpt_cdsys_xw_px_lw_kxj_fmj_jbj.firstinput_time
     *
     * @mbggenerated
     */
    public void setFirstinputTime(Date firstinputTime) {
        this.firstinputTime = firstinputTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_pxx_jcpt_cdsys_xw_px_lw_kxj_fmj_jbj.type
     *
     * @return the value of cas_pxx_jcpt_cdsys_xw_px_lw_kxj_fmj_jbj.type
     *
     * @mbggenerated
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_pxx_jcpt_cdsys_xw_px_lw_kxj_fmj_jbj.type
     *
     * @param type the value for cas_pxx_jcpt_cdsys_xw_px_lw_kxj_fmj_jbj.type
     *
     * @mbggenerated
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_pxx_jcpt_cdsys_xw_px_lw_kxj_fmj_jbj.datasource_type
     *
     * @return the value of cas_pxx_jcpt_cdsys_xw_px_lw_kxj_fmj_jbj.datasource_type
     *
     * @mbggenerated
     */
    public String getDatasourceType() {
        return datasourceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_pxx_jcpt_cdsys_xw_px_lw_kxj_fmj_jbj.datasource_type
     *
     * @param datasourceType the value for cas_pxx_jcpt_cdsys_xw_px_lw_kxj_fmj_jbj.datasource_type
     *
     * @mbggenerated
     */
    public void setDatasourceType(String datasourceType) {
        this.datasourceType = datasourceType == null ? null : datasourceType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_pxx_jcpt_cdsys_xw_px_lw_kxj_fmj_jbj.etl_datasource
     *
     * @return the value of cas_pxx_jcpt_cdsys_xw_px_lw_kxj_fmj_jbj.etl_datasource
     *
     * @mbggenerated
     */
    public String getEtlDatasource() {
        return etlDatasource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_pxx_jcpt_cdsys_xw_px_lw_kxj_fmj_jbj.etl_datasource
     *
     * @param etlDatasource the value for cas_pxx_jcpt_cdsys_xw_px_lw_kxj_fmj_jbj.etl_datasource
     *
     * @mbggenerated
     */
    public void setEtlDatasource(String etlDatasource) {
        this.etlDatasource = etlDatasource == null ? null : etlDatasource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_pxx_jcpt_cdsys_xw_px_lw_kxj_fmj_jbj.laterupdate_time
     *
     * @return the value of cas_pxx_jcpt_cdsys_xw_px_lw_kxj_fmj_jbj.laterupdate_time
     *
     * @mbggenerated
     */
    public Date getLaterupdateTime() {
        return laterupdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_pxx_jcpt_cdsys_xw_px_lw_kxj_fmj_jbj.laterupdate_time
     *
     * @param laterupdateTime the value for cas_pxx_jcpt_cdsys_xw_px_lw_kxj_fmj_jbj.laterupdate_time
     *
     * @mbggenerated
     */
    public void setLaterupdateTime(Date laterupdateTime) {
        this.laterupdateTime = laterupdateTime;
    }
}