package cn.arp.trend.entity.biz;

import java.util.Date;

public class CasPxxJfbj {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_pxx_jfbj.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_pxx_jfbj.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_pxx_jfbj.year
     *
     * @mbggenerated
     */
    private String year;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_pxx_jfbj.amount
     *
     * @mbggenerated
     */
    private Double amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_pxx_jfbj.jsys
     *
     * @mbggenerated
     */
    private String jsys;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_pxx_jfbj.finance_fund
     *
     * @mbggenerated
     */
    private Double financeFund;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_pxx_jfbj.firstinput_time
     *
     * @mbggenerated
     */
    private Date firstinputTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_pxx_jfbj.datasource_type
     *
     * @mbggenerated
     */
    private String datasourceType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_pxx_jfbj.etl_datasource
     *
     * @mbggenerated
     */
    private String etlDatasource;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cas_pxx_jfbj.laterupdate_time
     *
     * @mbggenerated
     */
    private Date laterupdateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_pxx_jfbj.id
     *
     * @return the value of cas_pxx_jfbj.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_pxx_jfbj.id
     *
     * @param id the value for cas_pxx_jfbj.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_pxx_jfbj.name
     *
     * @return the value of cas_pxx_jfbj.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_pxx_jfbj.name
     *
     * @param name the value for cas_pxx_jfbj.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_pxx_jfbj.year
     *
     * @return the value of cas_pxx_jfbj.year
     *
     * @mbggenerated
     */
    public String getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_pxx_jfbj.year
     *
     * @param year the value for cas_pxx_jfbj.year
     *
     * @mbggenerated
     */
    public void setYear(String year) {
        this.year = year == null ? null : year.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_pxx_jfbj.amount
     *
     * @return the value of cas_pxx_jfbj.amount
     *
     * @mbggenerated
     */
    public Double getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_pxx_jfbj.amount
     *
     * @param amount the value for cas_pxx_jfbj.amount
     *
     * @mbggenerated
     */
    public void setAmount(Double amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_pxx_jfbj.jsys
     *
     * @return the value of cas_pxx_jfbj.jsys
     *
     * @mbggenerated
     */
    public String getJsys() {
        return jsys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_pxx_jfbj.jsys
     *
     * @param jsys the value for cas_pxx_jfbj.jsys
     *
     * @mbggenerated
     */
    public void setJsys(String jsys) {
        this.jsys = jsys == null ? null : jsys.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_pxx_jfbj.finance_fund
     *
     * @return the value of cas_pxx_jfbj.finance_fund
     *
     * @mbggenerated
     */
    public Double getFinanceFund() {
        return financeFund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_pxx_jfbj.finance_fund
     *
     * @param financeFund the value for cas_pxx_jfbj.finance_fund
     *
     * @mbggenerated
     */
    public void setFinanceFund(Double financeFund) {
        this.financeFund = financeFund;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_pxx_jfbj.firstinput_time
     *
     * @return the value of cas_pxx_jfbj.firstinput_time
     *
     * @mbggenerated
     */
    public Date getFirstinputTime() {
        return firstinputTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_pxx_jfbj.firstinput_time
     *
     * @param firstinputTime the value for cas_pxx_jfbj.firstinput_time
     *
     * @mbggenerated
     */
    public void setFirstinputTime(Date firstinputTime) {
        this.firstinputTime = firstinputTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_pxx_jfbj.datasource_type
     *
     * @return the value of cas_pxx_jfbj.datasource_type
     *
     * @mbggenerated
     */
    public String getDatasourceType() {
        return datasourceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_pxx_jfbj.datasource_type
     *
     * @param datasourceType the value for cas_pxx_jfbj.datasource_type
     *
     * @mbggenerated
     */
    public void setDatasourceType(String datasourceType) {
        this.datasourceType = datasourceType == null ? null : datasourceType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_pxx_jfbj.etl_datasource
     *
     * @return the value of cas_pxx_jfbj.etl_datasource
     *
     * @mbggenerated
     */
    public String getEtlDatasource() {
        return etlDatasource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_pxx_jfbj.etl_datasource
     *
     * @param etlDatasource the value for cas_pxx_jfbj.etl_datasource
     *
     * @mbggenerated
     */
    public void setEtlDatasource(String etlDatasource) {
        this.etlDatasource = etlDatasource == null ? null : etlDatasource.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cas_pxx_jfbj.laterupdate_time
     *
     * @return the value of cas_pxx_jfbj.laterupdate_time
     *
     * @mbggenerated
     */
    public Date getLaterupdateTime() {
        return laterupdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cas_pxx_jfbj.laterupdate_time
     *
     * @param laterupdateTime the value for cas_pxx_jfbj.laterupdate_time
     *
     * @mbggenerated
     */
    public void setLaterupdateTime(Date laterupdateTime) {
        this.laterupdateTime = laterupdateTime;
    }
}