package cn.arp.trend.entity.biz;

import java.util.Date;

public class CasStatsScienceActivities {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_cas_stats_science_activities.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_cas_stats_science_activities.nf
     *
     * @mbggenerated
     */
    private String nf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_cas_stats_science_activities.rd
     *
     * @mbggenerated
     */
    private Double rd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_cas_stats_science_activities.jcyj
     *
     * @mbggenerated
     */
    private Double jcyj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_cas_stats_science_activities.bz
     *
     * @mbggenerated
     */
    private Double bz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column v_cas_stats_science_activities.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_cas_stats_science_activities.id
     *
     * @return the value of v_cas_stats_science_activities.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_cas_stats_science_activities.id
     *
     * @param id the value for v_cas_stats_science_activities.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_cas_stats_science_activities.nf
     *
     * @return the value of v_cas_stats_science_activities.nf
     *
     * @mbggenerated
     */
    public String getNf() {
        return nf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_cas_stats_science_activities.nf
     *
     * @param nf the value for v_cas_stats_science_activities.nf
     *
     * @mbggenerated
     */
    public void setNf(String nf) {
        this.nf = nf == null ? null : nf.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_cas_stats_science_activities.rd
     *
     * @return the value of v_cas_stats_science_activities.rd
     *
     * @mbggenerated
     */
    public Double getRd() {
        return rd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_cas_stats_science_activities.rd
     *
     * @param rd the value for v_cas_stats_science_activities.rd
     *
     * @mbggenerated
     */
    public void setRd(Double rd) {
        this.rd = rd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_cas_stats_science_activities.jcyj
     *
     * @return the value of v_cas_stats_science_activities.jcyj
     *
     * @mbggenerated
     */
    public Double getJcyj() {
        return jcyj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_cas_stats_science_activities.jcyj
     *
     * @param jcyj the value for v_cas_stats_science_activities.jcyj
     *
     * @mbggenerated
     */
    public void setJcyj(Double jcyj) {
        this.jcyj = jcyj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_cas_stats_science_activities.bz
     *
     * @return the value of v_cas_stats_science_activities.bz
     *
     * @mbggenerated
     */
    public Double getBz() {
        return bz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_cas_stats_science_activities.bz
     *
     * @param bz the value for v_cas_stats_science_activities.bz
     *
     * @mbggenerated
     */
    public void setBz(Double bz) {
        this.bz = bz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column v_cas_stats_science_activities.update_time
     *
     * @return the value of v_cas_stats_science_activities.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column v_cas_stats_science_activities.update_time
     *
     * @param updateTime the value for v_cas_stats_science_activities.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}