package cn.arp.trend.entity.biz;

public class IcCome {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ic_come.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ic_come.jgmc
     *
     * @mbggenerated
     */
    private String jgmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ic_come.jgbh
     *
     * @mbggenerated
     */
    private String jgbh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ic_come.field
     *
     * @mbggenerated
     */
    private String field;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ic_come.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ic_come.gender
     *
     * @mbggenerated
     */
    private String gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ic_come.birthday
     *
     * @mbggenerated
     */
    private String birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ic_come.nationality
     *
     * @mbggenerated
     */
    private String nationality;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ic_come.country
     *
     * @mbggenerated
     */
    private String country;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ic_come.ydyl
     *
     * @mbggenerated
     */
    private String ydyl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ic_come.form
     *
     * @mbggenerated
     */
    private String form;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ic_come.visit_date
     *
     * @mbggenerated
     */
    private String visitDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ic_come.number_of_team
     *
     * @mbggenerated
     */
    private Integer numberOfTeam;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ic_come.subject
     *
     * @mbggenerated
     */
    private String subject;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ic_come.id
     *
     * @return the value of ic_come.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ic_come.id
     *
     * @param id the value for ic_come.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ic_come.jgmc
     *
     * @return the value of ic_come.jgmc
     *
     * @mbggenerated
     */
    public String getJgmc() {
        return jgmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ic_come.jgmc
     *
     * @param jgmc the value for ic_come.jgmc
     *
     * @mbggenerated
     */
    public void setJgmc(String jgmc) {
        this.jgmc = jgmc == null ? null : jgmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ic_come.jgbh
     *
     * @return the value of ic_come.jgbh
     *
     * @mbggenerated
     */
    public String getJgbh() {
        return jgbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ic_come.jgbh
     *
     * @param jgbh the value for ic_come.jgbh
     *
     * @mbggenerated
     */
    public void setJgbh(String jgbh) {
        this.jgbh = jgbh == null ? null : jgbh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ic_come.field
     *
     * @return the value of ic_come.field
     *
     * @mbggenerated
     */
    public String getField() {
        return field;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ic_come.field
     *
     * @param field the value for ic_come.field
     *
     * @mbggenerated
     */
    public void setField(String field) {
        this.field = field == null ? null : field.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ic_come.name
     *
     * @return the value of ic_come.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ic_come.name
     *
     * @param name the value for ic_come.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ic_come.gender
     *
     * @return the value of ic_come.gender
     *
     * @mbggenerated
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ic_come.gender
     *
     * @param gender the value for ic_come.gender
     *
     * @mbggenerated
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ic_come.birthday
     *
     * @return the value of ic_come.birthday
     *
     * @mbggenerated
     */
    public String getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ic_come.birthday
     *
     * @param birthday the value for ic_come.birthday
     *
     * @mbggenerated
     */
    public void setBirthday(String birthday) {
        this.birthday = birthday == null ? null : birthday.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ic_come.nationality
     *
     * @return the value of ic_come.nationality
     *
     * @mbggenerated
     */
    public String getNationality() {
        return nationality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ic_come.nationality
     *
     * @param nationality the value for ic_come.nationality
     *
     * @mbggenerated
     */
    public void setNationality(String nationality) {
        this.nationality = nationality == null ? null : nationality.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ic_come.country
     *
     * @return the value of ic_come.country
     *
     * @mbggenerated
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ic_come.country
     *
     * @param country the value for ic_come.country
     *
     * @mbggenerated
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ic_come.ydyl
     *
     * @return the value of ic_come.ydyl
     *
     * @mbggenerated
     */
    public String getYdyl() {
        return ydyl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ic_come.ydyl
     *
     * @param ydyl the value for ic_come.ydyl
     *
     * @mbggenerated
     */
    public void setYdyl(String ydyl) {
        this.ydyl = ydyl == null ? null : ydyl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ic_come.form
     *
     * @return the value of ic_come.form
     *
     * @mbggenerated
     */
    public String getForm() {
        return form;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ic_come.form
     *
     * @param form the value for ic_come.form
     *
     * @mbggenerated
     */
    public void setForm(String form) {
        this.form = form == null ? null : form.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ic_come.visit_date
     *
     * @return the value of ic_come.visit_date
     *
     * @mbggenerated
     */
    public String getVisitDate() {
        return visitDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ic_come.visit_date
     *
     * @param visitDate the value for ic_come.visit_date
     *
     * @mbggenerated
     */
    public void setVisitDate(String visitDate) {
        this.visitDate = visitDate == null ? null : visitDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ic_come.number_of_team
     *
     * @return the value of ic_come.number_of_team
     *
     * @mbggenerated
     */
    public Integer getNumberOfTeam() {
        return numberOfTeam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ic_come.number_of_team
     *
     * @param numberOfTeam the value for ic_come.number_of_team
     *
     * @mbggenerated
     */
    public void setNumberOfTeam(Integer numberOfTeam) {
        this.numberOfTeam = numberOfTeam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ic_come.subject
     *
     * @return the value of ic_come.subject
     *
     * @mbggenerated
     */
    public String getSubject() {
        return subject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ic_come.subject
     *
     * @param subject the value for ic_come.subject
     *
     * @mbggenerated
     */
    public void setSubject(String subject) {
        this.subject = subject == null ? null : subject.trim();
    }
}