package cn.arp.trend.entity.biz;

public class RefEduGraduation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ref_edu_graduation.xh
     *
     * @mbggenerated
     */
    private String xh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ref_edu_graduation.jgbh
     *
     * @mbggenerated
     */
    private String jgbh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ref_edu_graduation.nf
     *
     * @mbggenerated
     */
    private String nf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ref_edu_graduation.jgmc
     *
     * @mbggenerated
     */
    private String jgmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ref_edu_graduation.lx
     *
     * @mbggenerated
     */
    private String lx;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ref_edu_graduation.xh
     *
     * @return the value of ref_edu_graduation.xh
     *
     * @mbggenerated
     */
    public String getXh() {
        return xh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ref_edu_graduation.xh
     *
     * @param xh the value for ref_edu_graduation.xh
     *
     * @mbggenerated
     */
    public void setXh(String xh) {
        this.xh = xh == null ? null : xh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ref_edu_graduation.jgbh
     *
     * @return the value of ref_edu_graduation.jgbh
     *
     * @mbggenerated
     */
    public String getJgbh() {
        return jgbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ref_edu_graduation.jgbh
     *
     * @param jgbh the value for ref_edu_graduation.jgbh
     *
     * @mbggenerated
     */
    public void setJgbh(String jgbh) {
        this.jgbh = jgbh == null ? null : jgbh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ref_edu_graduation.nf
     *
     * @return the value of ref_edu_graduation.nf
     *
     * @mbggenerated
     */
    public String getNf() {
        return nf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ref_edu_graduation.nf
     *
     * @param nf the value for ref_edu_graduation.nf
     *
     * @mbggenerated
     */
    public void setNf(String nf) {
        this.nf = nf == null ? null : nf.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ref_edu_graduation.jgmc
     *
     * @return the value of ref_edu_graduation.jgmc
     *
     * @mbggenerated
     */
    public String getJgmc() {
        return jgmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ref_edu_graduation.jgmc
     *
     * @param jgmc the value for ref_edu_graduation.jgmc
     *
     * @mbggenerated
     */
    public void setJgmc(String jgmc) {
        this.jgmc = jgmc == null ? null : jgmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ref_edu_graduation.lx
     *
     * @return the value of ref_edu_graduation.lx
     *
     * @mbggenerated
     */
    public String getLx() {
        return lx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ref_edu_graduation.lx
     *
     * @param lx the value for ref_edu_graduation.lx
     *
     * @mbggenerated
     */
    public void setLx(String lx) {
        this.lx = lx == null ? null : lx.trim();
    }
}