package cn.arp.trend.entity.biz;

public class RefOrgType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ref_org_type.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ref_org_type.jgmc
     *
     * @mbggenerated
     */
    private String jgmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ref_org_type.jgmc_en
     *
     * @mbggenerated
     */
    private String jgmcEn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ref_org_type.jgbh
     *
     * @mbggenerated
     */
    private String jgbh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ref_org_type.research_field
     *
     * @mbggenerated
     */
    private String researchField;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ref_org_type.sljg
     *
     * @mbggenerated
     */
    private String sljg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ref_org_type.sljgmc
     *
     * @mbggenerated
     */
    private String sljgmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ref_org_type.ssfy
     *
     * @mbggenerated
     */
    private String ssfy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ref_org_type.sssf
     *
     * @mbggenerated
     */
    private String sssf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ref_org_type.desc
     *
     * @mbggenerated
     */
    private String desc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ref_org_type.datasource_type
     *
     * @mbggenerated
     */
    private String datasourceType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ref_org_type.id
     *
     * @return the value of ref_org_type.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ref_org_type.id
     *
     * @param id the value for ref_org_type.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ref_org_type.jgmc
     *
     * @return the value of ref_org_type.jgmc
     *
     * @mbggenerated
     */
    public String getJgmc() {
        return jgmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ref_org_type.jgmc
     *
     * @param jgmc the value for ref_org_type.jgmc
     *
     * @mbggenerated
     */
    public void setJgmc(String jgmc) {
        this.jgmc = jgmc == null ? null : jgmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ref_org_type.jgmc_en
     *
     * @return the value of ref_org_type.jgmc_en
     *
     * @mbggenerated
     */
    public String getJgmcEn() {
        return jgmcEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ref_org_type.jgmc_en
     *
     * @param jgmcEn the value for ref_org_type.jgmc_en
     *
     * @mbggenerated
     */
    public void setJgmcEn(String jgmcEn) {
        this.jgmcEn = jgmcEn == null ? null : jgmcEn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ref_org_type.jgbh
     *
     * @return the value of ref_org_type.jgbh
     *
     * @mbggenerated
     */
    public String getJgbh() {
        return jgbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ref_org_type.jgbh
     *
     * @param jgbh the value for ref_org_type.jgbh
     *
     * @mbggenerated
     */
    public void setJgbh(String jgbh) {
        this.jgbh = jgbh == null ? null : jgbh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ref_org_type.research_field
     *
     * @return the value of ref_org_type.research_field
     *
     * @mbggenerated
     */
    public String getResearchField() {
        return researchField;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ref_org_type.research_field
     *
     * @param researchField the value for ref_org_type.research_field
     *
     * @mbggenerated
     */
    public void setResearchField(String researchField) {
        this.researchField = researchField == null ? null : researchField.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ref_org_type.sljg
     *
     * @return the value of ref_org_type.sljg
     *
     * @mbggenerated
     */
    public String getSljg() {
        return sljg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ref_org_type.sljg
     *
     * @param sljg the value for ref_org_type.sljg
     *
     * @mbggenerated
     */
    public void setSljg(String sljg) {
        this.sljg = sljg == null ? null : sljg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ref_org_type.sljgmc
     *
     * @return the value of ref_org_type.sljgmc
     *
     * @mbggenerated
     */
    public String getSljgmc() {
        return sljgmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ref_org_type.sljgmc
     *
     * @param sljgmc the value for ref_org_type.sljgmc
     *
     * @mbggenerated
     */
    public void setSljgmc(String sljgmc) {
        this.sljgmc = sljgmc == null ? null : sljgmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ref_org_type.ssfy
     *
     * @return the value of ref_org_type.ssfy
     *
     * @mbggenerated
     */
    public String getSsfy() {
        return ssfy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ref_org_type.ssfy
     *
     * @param ssfy the value for ref_org_type.ssfy
     *
     * @mbggenerated
     */
    public void setSsfy(String ssfy) {
        this.ssfy = ssfy == null ? null : ssfy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ref_org_type.sssf
     *
     * @return the value of ref_org_type.sssf
     *
     * @mbggenerated
     */
    public String getSssf() {
        return sssf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ref_org_type.sssf
     *
     * @param sssf the value for ref_org_type.sssf
     *
     * @mbggenerated
     */
    public void setSssf(String sssf) {
        this.sssf = sssf == null ? null : sssf.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ref_org_type.desc
     *
     * @return the value of ref_org_type.desc
     *
     * @mbggenerated
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ref_org_type.desc
     *
     * @param desc the value for ref_org_type.desc
     *
     * @mbggenerated
     */
    public void setDesc(String desc) {
        this.desc = desc == null ? null : desc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ref_org_type.datasource_type
     *
     * @return the value of ref_org_type.datasource_type
     *
     * @mbggenerated
     */
    public String getDatasourceType() {
        return datasourceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ref_org_type.datasource_type
     *
     * @param datasourceType the value for ref_org_type.datasource_type
     *
     * @mbggenerated
     */
    public void setDatasourceType(String datasourceType) {
        this.datasourceType = datasourceType == null ? null : datasourceType.trim();
    }
}