package cn.arp.trend.entity.biz;

public class StatCasTalentsProgram {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_cas_talents_program.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_cas_talents_program.jgmc
     *
     * @mbggenerated
     */
    private String jgmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_cas_talents_program.jgdm
     *
     * @mbggenerated
     */
    private String jgdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_cas_talents_program.ssly
     *
     * @mbggenerated
     */
    private String ssly;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_cas_talents_program.nf
     *
     * @mbggenerated
     */
    private String nf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_cas_talents_program.lj
     *
     * @mbggenerated
     */
    private Integer lj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_cas_talents_program.xz
     *
     * @mbggenerated
     */
    private Integer xz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_cas_talents_program.lx
     *
     * @mbggenerated
     */
    private Integer lx;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_cas_talents_program.id
     *
     * @return the value of stat_cas_talents_program.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_cas_talents_program.id
     *
     * @param id the value for stat_cas_talents_program.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_cas_talents_program.jgmc
     *
     * @return the value of stat_cas_talents_program.jgmc
     *
     * @mbggenerated
     */
    public String getJgmc() {
        return jgmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_cas_talents_program.jgmc
     *
     * @param jgmc the value for stat_cas_talents_program.jgmc
     *
     * @mbggenerated
     */
    public void setJgmc(String jgmc) {
        this.jgmc = jgmc == null ? null : jgmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_cas_talents_program.jgdm
     *
     * @return the value of stat_cas_talents_program.jgdm
     *
     * @mbggenerated
     */
    public String getJgdm() {
        return jgdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_cas_talents_program.jgdm
     *
     * @param jgdm the value for stat_cas_talents_program.jgdm
     *
     * @mbggenerated
     */
    public void setJgdm(String jgdm) {
        this.jgdm = jgdm == null ? null : jgdm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_cas_talents_program.ssly
     *
     * @return the value of stat_cas_talents_program.ssly
     *
     * @mbggenerated
     */
    public String getSsly() {
        return ssly;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_cas_talents_program.ssly
     *
     * @param ssly the value for stat_cas_talents_program.ssly
     *
     * @mbggenerated
     */
    public void setSsly(String ssly) {
        this.ssly = ssly == null ? null : ssly.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_cas_talents_program.nf
     *
     * @return the value of stat_cas_talents_program.nf
     *
     * @mbggenerated
     */
    public String getNf() {
        return nf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_cas_talents_program.nf
     *
     * @param nf the value for stat_cas_talents_program.nf
     *
     * @mbggenerated
     */
    public void setNf(String nf) {
        this.nf = nf == null ? null : nf.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_cas_talents_program.lj
     *
     * @return the value of stat_cas_talents_program.lj
     *
     * @mbggenerated
     */
    public Integer getLj() {
        return lj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_cas_talents_program.lj
     *
     * @param lj the value for stat_cas_talents_program.lj
     *
     * @mbggenerated
     */
    public void setLj(Integer lj) {
        this.lj = lj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_cas_talents_program.xz
     *
     * @return the value of stat_cas_talents_program.xz
     *
     * @mbggenerated
     */
    public Integer getXz() {
        return xz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_cas_talents_program.xz
     *
     * @param xz the value for stat_cas_talents_program.xz
     *
     * @mbggenerated
     */
    public void setXz(Integer xz) {
        this.xz = xz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_cas_talents_program.lx
     *
     * @return the value of stat_cas_talents_program.lx
     *
     * @mbggenerated
     */
    public Integer getLx() {
        return lx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_cas_talents_program.lx
     *
     * @param lx the value for stat_cas_talents_program.lx
     *
     * @mbggenerated
     */
    public void setLx(Integer lx) {
        this.lx = lx;
    }
}