package cn.arp.trend.entity.biz;

import java.util.Date;

public class StatArpStaffDuty {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_arp_staff_duty.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_arp_staff_duty.jgbh
     *
     * @mbggenerated
     */
    private String jgbh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_arp_staff_duty.jgmc
     *
     * @mbggenerated
     */
    private String jgmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_arp_staff_duty.nf
     *
     * @mbggenerated
     */
    private String nf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_arp_staff_duty.zs
     *
     * @mbggenerated
     */
    private Integer zs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_arp_staff_duty.zyjsry
     *
     * @mbggenerated
     */
    private Integer zyjsry;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_arp_staff_duty.xzglry
     *
     * @mbggenerated
     */
    private Integer xzglry;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_arp_staff_duty.gr
     *
     * @mbggenerated
     */
    private Integer gr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_arp_staff_duty.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_arp_staff_duty.id
     *
     * @return the value of stat_arp_staff_duty.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_arp_staff_duty.id
     *
     * @param id the value for stat_arp_staff_duty.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_arp_staff_duty.jgbh
     *
     * @return the value of stat_arp_staff_duty.jgbh
     *
     * @mbggenerated
     */
    public String getJgbh() {
        return jgbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_arp_staff_duty.jgbh
     *
     * @param jgbh the value for stat_arp_staff_duty.jgbh
     *
     * @mbggenerated
     */
    public void setJgbh(String jgbh) {
        this.jgbh = jgbh == null ? null : jgbh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_arp_staff_duty.jgmc
     *
     * @return the value of stat_arp_staff_duty.jgmc
     *
     * @mbggenerated
     */
    public String getJgmc() {
        return jgmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_arp_staff_duty.jgmc
     *
     * @param jgmc the value for stat_arp_staff_duty.jgmc
     *
     * @mbggenerated
     */
    public void setJgmc(String jgmc) {
        this.jgmc = jgmc == null ? null : jgmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_arp_staff_duty.nf
     *
     * @return the value of stat_arp_staff_duty.nf
     *
     * @mbggenerated
     */
    public String getNf() {
        return nf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_arp_staff_duty.nf
     *
     * @param nf the value for stat_arp_staff_duty.nf
     *
     * @mbggenerated
     */
    public void setNf(String nf) {
        this.nf = nf == null ? null : nf.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_arp_staff_duty.zs
     *
     * @return the value of stat_arp_staff_duty.zs
     *
     * @mbggenerated
     */
    public Integer getZs() {
        return zs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_arp_staff_duty.zs
     *
     * @param zs the value for stat_arp_staff_duty.zs
     *
     * @mbggenerated
     */
    public void setZs(Integer zs) {
        this.zs = zs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_arp_staff_duty.zyjsry
     *
     * @return the value of stat_arp_staff_duty.zyjsry
     *
     * @mbggenerated
     */
    public Integer getZyjsry() {
        return zyjsry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_arp_staff_duty.zyjsry
     *
     * @param zyjsry the value for stat_arp_staff_duty.zyjsry
     *
     * @mbggenerated
     */
    public void setZyjsry(Integer zyjsry) {
        this.zyjsry = zyjsry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_arp_staff_duty.xzglry
     *
     * @return the value of stat_arp_staff_duty.xzglry
     *
     * @mbggenerated
     */
    public Integer getXzglry() {
        return xzglry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_arp_staff_duty.xzglry
     *
     * @param xzglry the value for stat_arp_staff_duty.xzglry
     *
     * @mbggenerated
     */
    public void setXzglry(Integer xzglry) {
        this.xzglry = xzglry;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_arp_staff_duty.gr
     *
     * @return the value of stat_arp_staff_duty.gr
     *
     * @mbggenerated
     */
    public Integer getGr() {
        return gr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_arp_staff_duty.gr
     *
     * @param gr the value for stat_arp_staff_duty.gr
     *
     * @mbggenerated
     */
    public void setGr(Integer gr) {
        this.gr = gr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_arp_staff_duty.update_time
     *
     * @return the value of stat_arp_staff_duty.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_arp_staff_duty.update_time
     *
     * @param updateTime the value for stat_arp_staff_duty.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}