package cn.arp.trend.entity.biz;

public class StatChinaAward10yearFinalCount {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_china_award_10year_final_count.num
     *
     * @mbggenerated
     */
    private Long num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_china_award_10year_final_count.hjnf
     *
     * @mbggenerated
     */
    private String hjnf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_china_award_10year_final_count.jxlb
     *
     * @mbggenerated
     */
    private String jxlb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_china_award_10year_final_count.hjdj
     *
     * @mbggenerated
     */
    private String hjdj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_china_award_10year_final_count.first_wcdw
     *
     * @mbggenerated
     */
    private String firstWcdw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_china_award_10year_final_count.research_field
     *
     * @mbggenerated
     */
    private String researchField;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_china_award_10year_final_count.ssfy
     *
     * @mbggenerated
     */
    private String ssfy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_china_award_10year_final_count.second_wcdw
     *
     * @mbggenerated
     */
    private String secondWcdw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_china_award_10year_final_count.third_wcdw
     *
     * @mbggenerated
     */
    private String thirdWcdw;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_china_award_10year_final_count.num
     *
     * @return the value of stat_china_award_10year_final_count.num
     *
     * @mbggenerated
     */
    public Long getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_china_award_10year_final_count.num
     *
     * @param num the value for stat_china_award_10year_final_count.num
     *
     * @mbggenerated
     */
    public void setNum(Long num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_china_award_10year_final_count.hjnf
     *
     * @return the value of stat_china_award_10year_final_count.hjnf
     *
     * @mbggenerated
     */
    public String getHjnf() {
        return hjnf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_china_award_10year_final_count.hjnf
     *
     * @param hjnf the value for stat_china_award_10year_final_count.hjnf
     *
     * @mbggenerated
     */
    public void setHjnf(String hjnf) {
        this.hjnf = hjnf == null ? null : hjnf.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_china_award_10year_final_count.jxlb
     *
     * @return the value of stat_china_award_10year_final_count.jxlb
     *
     * @mbggenerated
     */
    public String getJxlb() {
        return jxlb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_china_award_10year_final_count.jxlb
     *
     * @param jxlb the value for stat_china_award_10year_final_count.jxlb
     *
     * @mbggenerated
     */
    public void setJxlb(String jxlb) {
        this.jxlb = jxlb == null ? null : jxlb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_china_award_10year_final_count.hjdj
     *
     * @return the value of stat_china_award_10year_final_count.hjdj
     *
     * @mbggenerated
     */
    public String getHjdj() {
        return hjdj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_china_award_10year_final_count.hjdj
     *
     * @param hjdj the value for stat_china_award_10year_final_count.hjdj
     *
     * @mbggenerated
     */
    public void setHjdj(String hjdj) {
        this.hjdj = hjdj == null ? null : hjdj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_china_award_10year_final_count.first_wcdw
     *
     * @return the value of stat_china_award_10year_final_count.first_wcdw
     *
     * @mbggenerated
     */
    public String getFirstWcdw() {
        return firstWcdw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_china_award_10year_final_count.first_wcdw
     *
     * @param firstWcdw the value for stat_china_award_10year_final_count.first_wcdw
     *
     * @mbggenerated
     */
    public void setFirstWcdw(String firstWcdw) {
        this.firstWcdw = firstWcdw == null ? null : firstWcdw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_china_award_10year_final_count.research_field
     *
     * @return the value of stat_china_award_10year_final_count.research_field
     *
     * @mbggenerated
     */
    public String getResearchField() {
        return researchField;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_china_award_10year_final_count.research_field
     *
     * @param researchField the value for stat_china_award_10year_final_count.research_field
     *
     * @mbggenerated
     */
    public void setResearchField(String researchField) {
        this.researchField = researchField == null ? null : researchField.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_china_award_10year_final_count.ssfy
     *
     * @return the value of stat_china_award_10year_final_count.ssfy
     *
     * @mbggenerated
     */
    public String getSsfy() {
        return ssfy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_china_award_10year_final_count.ssfy
     *
     * @param ssfy the value for stat_china_award_10year_final_count.ssfy
     *
     * @mbggenerated
     */
    public void setSsfy(String ssfy) {
        this.ssfy = ssfy == null ? null : ssfy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_china_award_10year_final_count.second_wcdw
     *
     * @return the value of stat_china_award_10year_final_count.second_wcdw
     *
     * @mbggenerated
     */
    public String getSecondWcdw() {
        return secondWcdw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_china_award_10year_final_count.second_wcdw
     *
     * @param secondWcdw the value for stat_china_award_10year_final_count.second_wcdw
     *
     * @mbggenerated
     */
    public void setSecondWcdw(String secondWcdw) {
        this.secondWcdw = secondWcdw == null ? null : secondWcdw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_china_award_10year_final_count.third_wcdw
     *
     * @return the value of stat_china_award_10year_final_count.third_wcdw
     *
     * @mbggenerated
     */
    public String getThirdWcdw() {
        return thirdWcdw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_china_award_10year_final_count.third_wcdw
     *
     * @param thirdWcdw the value for stat_china_award_10year_final_count.third_wcdw
     *
     * @mbggenerated
     */
    public void setThirdWcdw(String thirdWcdw) {
        this.thirdWcdw = thirdWcdw == null ? null : thirdWcdw.trim();
    }
}