package cn.arp.trend.entity.biz;

import java.util.Date;

public class StatArpStaffTechLevel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_arp_staff_tech_level.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_arp_staff_tech_level.jgbh
     *
     * @mbggenerated
     */
    private String jgbh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_arp_staff_tech_level.jgmc
     *
     * @mbggenerated
     */
    private String jgmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_arp_staff_tech_level.nf
     *
     * @mbggenerated
     */
    private String nf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_arp_staff_tech_level.gj
     *
     * @mbggenerated
     */
    private Integer gj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_arp_staff_tech_level.fg
     *
     * @mbggenerated
     */
    private Integer fg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_arp_staff_tech_level.zj
     *
     * @mbggenerated
     */
    private Integer zj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_arp_staff_tech_level.cj
     *
     * @mbggenerated
     */
    private Integer cj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_arp_staff_tech_level.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_arp_staff_tech_level.id
     *
     * @return the value of stat_arp_staff_tech_level.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_arp_staff_tech_level.id
     *
     * @param id the value for stat_arp_staff_tech_level.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_arp_staff_tech_level.jgbh
     *
     * @return the value of stat_arp_staff_tech_level.jgbh
     *
     * @mbggenerated
     */
    public String getJgbh() {
        return jgbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_arp_staff_tech_level.jgbh
     *
     * @param jgbh the value for stat_arp_staff_tech_level.jgbh
     *
     * @mbggenerated
     */
    public void setJgbh(String jgbh) {
        this.jgbh = jgbh == null ? null : jgbh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_arp_staff_tech_level.jgmc
     *
     * @return the value of stat_arp_staff_tech_level.jgmc
     *
     * @mbggenerated
     */
    public String getJgmc() {
        return jgmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_arp_staff_tech_level.jgmc
     *
     * @param jgmc the value for stat_arp_staff_tech_level.jgmc
     *
     * @mbggenerated
     */
    public void setJgmc(String jgmc) {
        this.jgmc = jgmc == null ? null : jgmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_arp_staff_tech_level.nf
     *
     * @return the value of stat_arp_staff_tech_level.nf
     *
     * @mbggenerated
     */
    public String getNf() {
        return nf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_arp_staff_tech_level.nf
     *
     * @param nf the value for stat_arp_staff_tech_level.nf
     *
     * @mbggenerated
     */
    public void setNf(String nf) {
        this.nf = nf == null ? null : nf.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_arp_staff_tech_level.gj
     *
     * @return the value of stat_arp_staff_tech_level.gj
     *
     * @mbggenerated
     */
    public Integer getGj() {
        return gj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_arp_staff_tech_level.gj
     *
     * @param gj the value for stat_arp_staff_tech_level.gj
     *
     * @mbggenerated
     */
    public void setGj(Integer gj) {
        this.gj = gj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_arp_staff_tech_level.fg
     *
     * @return the value of stat_arp_staff_tech_level.fg
     *
     * @mbggenerated
     */
    public Integer getFg() {
        return fg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_arp_staff_tech_level.fg
     *
     * @param fg the value for stat_arp_staff_tech_level.fg
     *
     * @mbggenerated
     */
    public void setFg(Integer fg) {
        this.fg = fg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_arp_staff_tech_level.zj
     *
     * @return the value of stat_arp_staff_tech_level.zj
     *
     * @mbggenerated
     */
    public Integer getZj() {
        return zj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_arp_staff_tech_level.zj
     *
     * @param zj the value for stat_arp_staff_tech_level.zj
     *
     * @mbggenerated
     */
    public void setZj(Integer zj) {
        this.zj = zj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_arp_staff_tech_level.cj
     *
     * @return the value of stat_arp_staff_tech_level.cj
     *
     * @mbggenerated
     */
    public Integer getCj() {
        return cj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_arp_staff_tech_level.cj
     *
     * @param cj the value for stat_arp_staff_tech_level.cj
     *
     * @mbggenerated
     */
    public void setCj(Integer cj) {
        this.cj = cj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_arp_staff_tech_level.update_time
     *
     * @return the value of stat_arp_staff_tech_level.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_arp_staff_tech_level.update_time
     *
     * @param updateTime the value for stat_arp_staff_tech_level.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}