package cn.arp.trend.entity.biz;

import java.util.Date;

public class StatArpStaffAge {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_arp_staff_age.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_arp_staff_age.jgbh
     *
     * @mbggenerated
     */
    private String jgbh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_arp_staff_age.jgmc
     *
     * @mbggenerated
     */
    private String jgmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_arp_staff_age.nf
     *
     * @mbggenerated
     */
    private String nf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_arp_staff_age.gw
     *
     * @mbggenerated
     */
    private String gw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_arp_staff_age.nld
     *
     * @mbggenerated
     */
    private String nld;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_arp_staff_age.rs
     *
     * @mbggenerated
     */
    private Integer rs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_arp_staff_age.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_arp_staff_age.id
     *
     * @return the value of stat_arp_staff_age.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_arp_staff_age.id
     *
     * @param id the value for stat_arp_staff_age.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_arp_staff_age.jgbh
     *
     * @return the value of stat_arp_staff_age.jgbh
     *
     * @mbggenerated
     */
    public String getJgbh() {
        return jgbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_arp_staff_age.jgbh
     *
     * @param jgbh the value for stat_arp_staff_age.jgbh
     *
     * @mbggenerated
     */
    public void setJgbh(String jgbh) {
        this.jgbh = jgbh == null ? null : jgbh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_arp_staff_age.jgmc
     *
     * @return the value of stat_arp_staff_age.jgmc
     *
     * @mbggenerated
     */
    public String getJgmc() {
        return jgmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_arp_staff_age.jgmc
     *
     * @param jgmc the value for stat_arp_staff_age.jgmc
     *
     * @mbggenerated
     */
    public void setJgmc(String jgmc) {
        this.jgmc = jgmc == null ? null : jgmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_arp_staff_age.nf
     *
     * @return the value of stat_arp_staff_age.nf
     *
     * @mbggenerated
     */
    public String getNf() {
        return nf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_arp_staff_age.nf
     *
     * @param nf the value for stat_arp_staff_age.nf
     *
     * @mbggenerated
     */
    public void setNf(String nf) {
        this.nf = nf == null ? null : nf.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_arp_staff_age.gw
     *
     * @return the value of stat_arp_staff_age.gw
     *
     * @mbggenerated
     */
    public String getGw() {
        return gw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_arp_staff_age.gw
     *
     * @param gw the value for stat_arp_staff_age.gw
     *
     * @mbggenerated
     */
    public void setGw(String gw) {
        this.gw = gw == null ? null : gw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_arp_staff_age.nld
     *
     * @return the value of stat_arp_staff_age.nld
     *
     * @mbggenerated
     */
    public String getNld() {
        return nld;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_arp_staff_age.nld
     *
     * @param nld the value for stat_arp_staff_age.nld
     *
     * @mbggenerated
     */
    public void setNld(String nld) {
        this.nld = nld == null ? null : nld.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_arp_staff_age.rs
     *
     * @return the value of stat_arp_staff_age.rs
     *
     * @mbggenerated
     */
    public Integer getRs() {
        return rs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_arp_staff_age.rs
     *
     * @param rs the value for stat_arp_staff_age.rs
     *
     * @mbggenerated
     */
    public void setRs(Integer rs) {
        this.rs = rs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_arp_staff_age.update_time
     *
     * @return the value of stat_arp_staff_age.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_arp_staff_age.update_time
     *
     * @param updateTime the value for stat_arp_staff_age.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}