package cn.arp.trend.entity.biz;

import java.util.Date;

public class StatArpStaffEducation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_arp_staff_education.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_arp_staff_education.jgbh
     *
     * @mbggenerated
     */
    private String jgbh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_arp_staff_education.jgmc
     *
     * @mbggenerated
     */
    private String jgmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_arp_staff_education.nf
     *
     * @mbggenerated
     */
    private String nf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_arp_staff_education.zw
     *
     * @mbggenerated
     */
    private String zw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_arp_staff_education.xl
     *
     * @mbggenerated
     */
    private String xl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_arp_staff_education.rs
     *
     * @mbggenerated
     */
    private Integer rs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_arp_staff_education.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_arp_staff_education.id
     *
     * @return the value of stat_arp_staff_education.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_arp_staff_education.id
     *
     * @param id the value for stat_arp_staff_education.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_arp_staff_education.jgbh
     *
     * @return the value of stat_arp_staff_education.jgbh
     *
     * @mbggenerated
     */
    public String getJgbh() {
        return jgbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_arp_staff_education.jgbh
     *
     * @param jgbh the value for stat_arp_staff_education.jgbh
     *
     * @mbggenerated
     */
    public void setJgbh(String jgbh) {
        this.jgbh = jgbh == null ? null : jgbh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_arp_staff_education.jgmc
     *
     * @return the value of stat_arp_staff_education.jgmc
     *
     * @mbggenerated
     */
    public String getJgmc() {
        return jgmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_arp_staff_education.jgmc
     *
     * @param jgmc the value for stat_arp_staff_education.jgmc
     *
     * @mbggenerated
     */
    public void setJgmc(String jgmc) {
        this.jgmc = jgmc == null ? null : jgmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_arp_staff_education.nf
     *
     * @return the value of stat_arp_staff_education.nf
     *
     * @mbggenerated
     */
    public String getNf() {
        return nf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_arp_staff_education.nf
     *
     * @param nf the value for stat_arp_staff_education.nf
     *
     * @mbggenerated
     */
    public void setNf(String nf) {
        this.nf = nf == null ? null : nf.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_arp_staff_education.zw
     *
     * @return the value of stat_arp_staff_education.zw
     *
     * @mbggenerated
     */
    public String getZw() {
        return zw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_arp_staff_education.zw
     *
     * @param zw the value for stat_arp_staff_education.zw
     *
     * @mbggenerated
     */
    public void setZw(String zw) {
        this.zw = zw == null ? null : zw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_arp_staff_education.xl
     *
     * @return the value of stat_arp_staff_education.xl
     *
     * @mbggenerated
     */
    public String getXl() {
        return xl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_arp_staff_education.xl
     *
     * @param xl the value for stat_arp_staff_education.xl
     *
     * @mbggenerated
     */
    public void setXl(String xl) {
        this.xl = xl == null ? null : xl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_arp_staff_education.rs
     *
     * @return the value of stat_arp_staff_education.rs
     *
     * @mbggenerated
     */
    public Integer getRs() {
        return rs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_arp_staff_education.rs
     *
     * @param rs the value for stat_arp_staff_education.rs
     *
     * @mbggenerated
     */
    public void setRs(Integer rs) {
        this.rs = rs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_arp_staff_education.update_time
     *
     * @return the value of stat_arp_staff_education.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_arp_staff_education.update_time
     *
     * @param updateTime the value for stat_arp_staff_education.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}