package cn.arp.trend.entity.biz;

public class StatMostProject {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_most_project.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_most_project.jgmc
     *
     * @mbggenerated
     */
    private String jgmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_most_project.nf
     *
     * @mbggenerated
     */
    private String nf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_most_project.xzxms
     *
     * @mbggenerated
     */
    private Long xzxms;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_most_project.xzxm_zjf
     *
     * @mbggenerated
     */
    private Double xzxmZjf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_most_project.datasource_type
     *
     * @mbggenerated
     */
    private String datasourceType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_most_project.id
     *
     * @return the value of stat_most_project.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_most_project.id
     *
     * @param id the value for stat_most_project.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_most_project.jgmc
     *
     * @return the value of stat_most_project.jgmc
     *
     * @mbggenerated
     */
    public String getJgmc() {
        return jgmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_most_project.jgmc
     *
     * @param jgmc the value for stat_most_project.jgmc
     *
     * @mbggenerated
     */
    public void setJgmc(String jgmc) {
        this.jgmc = jgmc == null ? null : jgmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_most_project.nf
     *
     * @return the value of stat_most_project.nf
     *
     * @mbggenerated
     */
    public String getNf() {
        return nf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_most_project.nf
     *
     * @param nf the value for stat_most_project.nf
     *
     * @mbggenerated
     */
    public void setNf(String nf) {
        this.nf = nf == null ? null : nf.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_most_project.xzxms
     *
     * @return the value of stat_most_project.xzxms
     *
     * @mbggenerated
     */
    public Long getXzxms() {
        return xzxms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_most_project.xzxms
     *
     * @param xzxms the value for stat_most_project.xzxms
     *
     * @mbggenerated
     */
    public void setXzxms(Long xzxms) {
        this.xzxms = xzxms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_most_project.xzxm_zjf
     *
     * @return the value of stat_most_project.xzxm_zjf
     *
     * @mbggenerated
     */
    public Double getXzxmZjf() {
        return xzxmZjf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_most_project.xzxm_zjf
     *
     * @param xzxmZjf the value for stat_most_project.xzxm_zjf
     *
     * @mbggenerated
     */
    public void setXzxmZjf(Double xzxmZjf) {
        this.xzxmZjf = xzxmZjf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_most_project.datasource_type
     *
     * @return the value of stat_most_project.datasource_type
     *
     * @mbggenerated
     */
    public String getDatasourceType() {
        return datasourceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_most_project.datasource_type
     *
     * @param datasourceType the value for stat_most_project.datasource_type
     *
     * @mbggenerated
     */
    public void setDatasourceType(String datasourceType) {
        this.datasourceType = datasourceType == null ? null : datasourceType.trim();
    }
}