package cn.arp.trend.entity.biz;

public class StatCasStaffQianzaiyearcountBydanwei extends StatCasStaffQianzaiyearcountBydanweiKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_cas_staff_qianzaiyearcount_bydanwei.jgmc
     *
     * @mbggenerated
     */
    private String jgmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_cas_staff_qianzaiyearcount_bydanwei.count
     *
     * @mbggenerated
     */
    private Long count;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_cas_staff_qianzaiyearcount_bydanwei.jgmc
     *
     * @return the value of stat_cas_staff_qianzaiyearcount_bydanwei.jgmc
     *
     * @mbggenerated
     */
    public String getJgmc() {
        return jgmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_cas_staff_qianzaiyearcount_bydanwei.jgmc
     *
     * @param jgmc the value for stat_cas_staff_qianzaiyearcount_bydanwei.jgmc
     *
     * @mbggenerated
     */
    public void setJgmc(String jgmc) {
        this.jgmc = jgmc == null ? null : jgmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_cas_staff_qianzaiyearcount_bydanwei.count
     *
     * @return the value of stat_cas_staff_qianzaiyearcount_bydanwei.count
     *
     * @mbggenerated
     */
    public Long getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_cas_staff_qianzaiyearcount_bydanwei.count
     *
     * @param count the value for stat_cas_staff_qianzaiyearcount_bydanwei.count
     *
     * @mbggenerated
     */
    public void setCount(Long count) {
        this.count = count;
    }
}