package cn.arp.trend.entity.biz;

import java.util.Date;

public class StatArpStaffPromotion {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_arp_staff_promotion.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_arp_staff_promotion.jgbh
     *
     * @mbggenerated
     */
    private String jgbh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_arp_staff_promotion.jgmc
     *
     * @mbggenerated
     */
    private String jgmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_arp_staff_promotion.nf
     *
     * @mbggenerated
     */
    private String nf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_arp_staff_promotion.gw
     *
     * @mbggenerated
     */
    private String gw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_arp_staff_promotion.nx
     *
     * @mbggenerated
     */
    private String nx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_arp_staff_promotion.fgzg
     *
     * @mbggenerated
     */
    private Integer fgzg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_arp_staff_promotion.zjfg
     *
     * @mbggenerated
     */
    private Integer zjfg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_arp_staff_promotion.cjzj
     *
     * @mbggenerated
     */
    private Integer cjzj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_arp_staff_promotion.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_arp_staff_promotion.id
     *
     * @return the value of stat_arp_staff_promotion.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_arp_staff_promotion.id
     *
     * @param id the value for stat_arp_staff_promotion.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_arp_staff_promotion.jgbh
     *
     * @return the value of stat_arp_staff_promotion.jgbh
     *
     * @mbggenerated
     */
    public String getJgbh() {
        return jgbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_arp_staff_promotion.jgbh
     *
     * @param jgbh the value for stat_arp_staff_promotion.jgbh
     *
     * @mbggenerated
     */
    public void setJgbh(String jgbh) {
        this.jgbh = jgbh == null ? null : jgbh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_arp_staff_promotion.jgmc
     *
     * @return the value of stat_arp_staff_promotion.jgmc
     *
     * @mbggenerated
     */
    public String getJgmc() {
        return jgmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_arp_staff_promotion.jgmc
     *
     * @param jgmc the value for stat_arp_staff_promotion.jgmc
     *
     * @mbggenerated
     */
    public void setJgmc(String jgmc) {
        this.jgmc = jgmc == null ? null : jgmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_arp_staff_promotion.nf
     *
     * @return the value of stat_arp_staff_promotion.nf
     *
     * @mbggenerated
     */
    public String getNf() {
        return nf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_arp_staff_promotion.nf
     *
     * @param nf the value for stat_arp_staff_promotion.nf
     *
     * @mbggenerated
     */
    public void setNf(String nf) {
        this.nf = nf == null ? null : nf.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_arp_staff_promotion.gw
     *
     * @return the value of stat_arp_staff_promotion.gw
     *
     * @mbggenerated
     */
    public String getGw() {
        return gw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_arp_staff_promotion.gw
     *
     * @param gw the value for stat_arp_staff_promotion.gw
     *
     * @mbggenerated
     */
    public void setGw(String gw) {
        this.gw = gw == null ? null : gw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_arp_staff_promotion.nx
     *
     * @return the value of stat_arp_staff_promotion.nx
     *
     * @mbggenerated
     */
    public String getNx() {
        return nx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_arp_staff_promotion.nx
     *
     * @param nx the value for stat_arp_staff_promotion.nx
     *
     * @mbggenerated
     */
    public void setNx(String nx) {
        this.nx = nx == null ? null : nx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_arp_staff_promotion.fgzg
     *
     * @return the value of stat_arp_staff_promotion.fgzg
     *
     * @mbggenerated
     */
    public Integer getFgzg() {
        return fgzg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_arp_staff_promotion.fgzg
     *
     * @param fgzg the value for stat_arp_staff_promotion.fgzg
     *
     * @mbggenerated
     */
    public void setFgzg(Integer fgzg) {
        this.fgzg = fgzg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_arp_staff_promotion.zjfg
     *
     * @return the value of stat_arp_staff_promotion.zjfg
     *
     * @mbggenerated
     */
    public Integer getZjfg() {
        return zjfg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_arp_staff_promotion.zjfg
     *
     * @param zjfg the value for stat_arp_staff_promotion.zjfg
     *
     * @mbggenerated
     */
    public void setZjfg(Integer zjfg) {
        this.zjfg = zjfg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_arp_staff_promotion.cjzj
     *
     * @return the value of stat_arp_staff_promotion.cjzj
     *
     * @mbggenerated
     */
    public Integer getCjzj() {
        return cjzj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_arp_staff_promotion.cjzj
     *
     * @param cjzj the value for stat_arp_staff_promotion.cjzj
     *
     * @mbggenerated
     */
    public void setCjzj(Integer cjzj) {
        this.cjzj = cjzj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_arp_staff_promotion.update_time
     *
     * @return the value of stat_arp_staff_promotion.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_arp_staff_promotion.update_time
     *
     * @param updateTime the value for stat_arp_staff_promotion.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}