package cn.arp.trend.entity.biz;

import java.util.Date;

public class StatArpStaffPost {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_arp_staff_post.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_arp_staff_post.jgbh
     *
     * @mbggenerated
     */
    private String jgbh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_arp_staff_post.jgmc
     *
     * @mbggenerated
     */
    private String jgmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_arp_staff_post.nf
     *
     * @mbggenerated
     */
    private String nf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_arp_staff_post.ky
     *
     * @mbggenerated
     */
    private Integer ky;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_arp_staff_post.gl
     *
     * @mbggenerated
     */
    private Integer gl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_arp_staff_post.zc
     *
     * @mbggenerated
     */
    private Integer zc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_arp_staff_post.qt
     *
     * @mbggenerated
     */
    private Integer qt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_arp_staff_post.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_arp_staff_post.id
     *
     * @return the value of stat_arp_staff_post.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_arp_staff_post.id
     *
     * @param id the value for stat_arp_staff_post.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_arp_staff_post.jgbh
     *
     * @return the value of stat_arp_staff_post.jgbh
     *
     * @mbggenerated
     */
    public String getJgbh() {
        return jgbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_arp_staff_post.jgbh
     *
     * @param jgbh the value for stat_arp_staff_post.jgbh
     *
     * @mbggenerated
     */
    public void setJgbh(String jgbh) {
        this.jgbh = jgbh == null ? null : jgbh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_arp_staff_post.jgmc
     *
     * @return the value of stat_arp_staff_post.jgmc
     *
     * @mbggenerated
     */
    public String getJgmc() {
        return jgmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_arp_staff_post.jgmc
     *
     * @param jgmc the value for stat_arp_staff_post.jgmc
     *
     * @mbggenerated
     */
    public void setJgmc(String jgmc) {
        this.jgmc = jgmc == null ? null : jgmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_arp_staff_post.nf
     *
     * @return the value of stat_arp_staff_post.nf
     *
     * @mbggenerated
     */
    public String getNf() {
        return nf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_arp_staff_post.nf
     *
     * @param nf the value for stat_arp_staff_post.nf
     *
     * @mbggenerated
     */
    public void setNf(String nf) {
        this.nf = nf == null ? null : nf.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_arp_staff_post.ky
     *
     * @return the value of stat_arp_staff_post.ky
     *
     * @mbggenerated
     */
    public Integer getKy() {
        return ky;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_arp_staff_post.ky
     *
     * @param ky the value for stat_arp_staff_post.ky
     *
     * @mbggenerated
     */
    public void setKy(Integer ky) {
        this.ky = ky;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_arp_staff_post.gl
     *
     * @return the value of stat_arp_staff_post.gl
     *
     * @mbggenerated
     */
    public Integer getGl() {
        return gl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_arp_staff_post.gl
     *
     * @param gl the value for stat_arp_staff_post.gl
     *
     * @mbggenerated
     */
    public void setGl(Integer gl) {
        this.gl = gl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_arp_staff_post.zc
     *
     * @return the value of stat_arp_staff_post.zc
     *
     * @mbggenerated
     */
    public Integer getZc() {
        return zc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_arp_staff_post.zc
     *
     * @param zc the value for stat_arp_staff_post.zc
     *
     * @mbggenerated
     */
    public void setZc(Integer zc) {
        this.zc = zc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_arp_staff_post.qt
     *
     * @return the value of stat_arp_staff_post.qt
     *
     * @mbggenerated
     */
    public Integer getQt() {
        return qt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_arp_staff_post.qt
     *
     * @param qt the value for stat_arp_staff_post.qt
     *
     * @mbggenerated
     */
    public void setQt(Integer qt) {
        this.qt = qt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_arp_staff_post.update_time
     *
     * @return the value of stat_arp_staff_post.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_arp_staff_post.update_time
     *
     * @param updateTime the value for stat_arp_staff_post.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}