package cn.arp.trend.entity.biz;

import java.util.Date;

public class StatArpFinIncome {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_arp_fin_income.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_arp_fin_income.jgbh
     *
     * @mbggenerated
     */
    private String jgbh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_arp_fin_income.jgmc
     *
     * @mbggenerated
     */
    private String jgmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_arp_fin_income.nf
     *
     * @mbggenerated
     */
    private String nf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_arp_fin_income.srhj
     *
     * @mbggenerated
     */
    private Double srhj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_arp_fin_income.czbz
     *
     * @mbggenerated
     */
    private Double czbz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_arp_fin_income.sysr
     *
     * @mbggenerated
     */
    private Double sysr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_arp_fin_income.jysr
     *
     * @mbggenerated
     */
    private Double jysr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_arp_fin_income.qtsr
     *
     * @mbggenerated
     */
    private Double qtsr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_arp_fin_income.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_arp_fin_income.id
     *
     * @return the value of stat_arp_fin_income.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_arp_fin_income.id
     *
     * @param id the value for stat_arp_fin_income.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_arp_fin_income.jgbh
     *
     * @return the value of stat_arp_fin_income.jgbh
     *
     * @mbggenerated
     */
    public String getJgbh() {
        return jgbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_arp_fin_income.jgbh
     *
     * @param jgbh the value for stat_arp_fin_income.jgbh
     *
     * @mbggenerated
     */
    public void setJgbh(String jgbh) {
        this.jgbh = jgbh == null ? null : jgbh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_arp_fin_income.jgmc
     *
     * @return the value of stat_arp_fin_income.jgmc
     *
     * @mbggenerated
     */
    public String getJgmc() {
        return jgmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_arp_fin_income.jgmc
     *
     * @param jgmc the value for stat_arp_fin_income.jgmc
     *
     * @mbggenerated
     */
    public void setJgmc(String jgmc) {
        this.jgmc = jgmc == null ? null : jgmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_arp_fin_income.nf
     *
     * @return the value of stat_arp_fin_income.nf
     *
     * @mbggenerated
     */
    public String getNf() {
        return nf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_arp_fin_income.nf
     *
     * @param nf the value for stat_arp_fin_income.nf
     *
     * @mbggenerated
     */
    public void setNf(String nf) {
        this.nf = nf == null ? null : nf.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_arp_fin_income.srhj
     *
     * @return the value of stat_arp_fin_income.srhj
     *
     * @mbggenerated
     */
    public Double getSrhj() {
        return srhj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_arp_fin_income.srhj
     *
     * @param srhj the value for stat_arp_fin_income.srhj
     *
     * @mbggenerated
     */
    public void setSrhj(Double srhj) {
        this.srhj = srhj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_arp_fin_income.czbz
     *
     * @return the value of stat_arp_fin_income.czbz
     *
     * @mbggenerated
     */
    public Double getCzbz() {
        return czbz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_arp_fin_income.czbz
     *
     * @param czbz the value for stat_arp_fin_income.czbz
     *
     * @mbggenerated
     */
    public void setCzbz(Double czbz) {
        this.czbz = czbz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_arp_fin_income.sysr
     *
     * @return the value of stat_arp_fin_income.sysr
     *
     * @mbggenerated
     */
    public Double getSysr() {
        return sysr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_arp_fin_income.sysr
     *
     * @param sysr the value for stat_arp_fin_income.sysr
     *
     * @mbggenerated
     */
    public void setSysr(Double sysr) {
        this.sysr = sysr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_arp_fin_income.jysr
     *
     * @return the value of stat_arp_fin_income.jysr
     *
     * @mbggenerated
     */
    public Double getJysr() {
        return jysr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_arp_fin_income.jysr
     *
     * @param jysr the value for stat_arp_fin_income.jysr
     *
     * @mbggenerated
     */
    public void setJysr(Double jysr) {
        this.jysr = jysr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_arp_fin_income.qtsr
     *
     * @return the value of stat_arp_fin_income.qtsr
     *
     * @mbggenerated
     */
    public Double getQtsr() {
        return qtsr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_arp_fin_income.qtsr
     *
     * @param qtsr the value for stat_arp_fin_income.qtsr
     *
     * @mbggenerated
     */
    public void setQtsr(Double qtsr) {
        this.qtsr = qtsr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_arp_fin_income.update_time
     *
     * @return the value of stat_arp_fin_income.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_arp_fin_income.update_time
     *
     * @param updateTime the value for stat_arp_fin_income.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}