package cn.arp.trend.entity.biz;

public class StatCasPaper {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_cas_paper.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_cas_paper.jgbh
     *
     * @mbggenerated
     */
    private String jgbh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_cas_paper.jgmc_ori
     *
     * @mbggenerated
     */
    private String jgmcOri;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_cas_paper.jgmc
     *
     * @mbggenerated
     */
    private String jgmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_cas_paper.nf
     *
     * @mbggenerated
     */
    private String nf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_cas_paper.lws
     *
     * @mbggenerated
     */
    private Integer lws;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_cas_paper.id
     *
     * @return the value of stat_cas_paper.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_cas_paper.id
     *
     * @param id the value for stat_cas_paper.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_cas_paper.jgbh
     *
     * @return the value of stat_cas_paper.jgbh
     *
     * @mbggenerated
     */
    public String getJgbh() {
        return jgbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_cas_paper.jgbh
     *
     * @param jgbh the value for stat_cas_paper.jgbh
     *
     * @mbggenerated
     */
    public void setJgbh(String jgbh) {
        this.jgbh = jgbh == null ? null : jgbh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_cas_paper.jgmc_ori
     *
     * @return the value of stat_cas_paper.jgmc_ori
     *
     * @mbggenerated
     */
    public String getJgmcOri() {
        return jgmcOri;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_cas_paper.jgmc_ori
     *
     * @param jgmcOri the value for stat_cas_paper.jgmc_ori
     *
     * @mbggenerated
     */
    public void setJgmcOri(String jgmcOri) {
        this.jgmcOri = jgmcOri == null ? null : jgmcOri.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_cas_paper.jgmc
     *
     * @return the value of stat_cas_paper.jgmc
     *
     * @mbggenerated
     */
    public String getJgmc() {
        return jgmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_cas_paper.jgmc
     *
     * @param jgmc the value for stat_cas_paper.jgmc
     *
     * @mbggenerated
     */
    public void setJgmc(String jgmc) {
        this.jgmc = jgmc == null ? null : jgmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_cas_paper.nf
     *
     * @return the value of stat_cas_paper.nf
     *
     * @mbggenerated
     */
    public String getNf() {
        return nf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_cas_paper.nf
     *
     * @param nf the value for stat_cas_paper.nf
     *
     * @mbggenerated
     */
    public void setNf(String nf) {
        this.nf = nf == null ? null : nf.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_cas_paper.lws
     *
     * @return the value of stat_cas_paper.lws
     *
     * @mbggenerated
     */
    public Integer getLws() {
        return lws;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_cas_paper.lws
     *
     * @param lws the value for stat_cas_paper.lws
     *
     * @mbggenerated
     */
    public void setLws(Integer lws) {
        this.lws = lws;
    }
}