package cn.arp.trend.entity.biz;

public class StatTeacherStudent {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_teacher_student.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_teacher_student.jgmc
     *
     * @mbggenerated
     */
    private String jgmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_teacher_student.jgbh
     *
     * @mbggenerated
     */
    private String jgbh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_teacher_student.nf
     *
     * @mbggenerated
     */
    private String nf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_teacher_student.bdrs
     *
     * @mbggenerated
     */
    private Integer bdrs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_teacher_student.bsrs
     *
     * @mbggenerated
     */
    private Integer bsrs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_teacher_student.sdrs
     *
     * @mbggenerated
     */
    private Integer sdrs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_teacher_student.ssrs
     *
     * @mbggenerated
     */
    private String ssrs;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_teacher_student.id
     *
     * @return the value of stat_teacher_student.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_teacher_student.id
     *
     * @param id the value for stat_teacher_student.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_teacher_student.jgmc
     *
     * @return the value of stat_teacher_student.jgmc
     *
     * @mbggenerated
     */
    public String getJgmc() {
        return jgmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_teacher_student.jgmc
     *
     * @param jgmc the value for stat_teacher_student.jgmc
     *
     * @mbggenerated
     */
    public void setJgmc(String jgmc) {
        this.jgmc = jgmc == null ? null : jgmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_teacher_student.jgbh
     *
     * @return the value of stat_teacher_student.jgbh
     *
     * @mbggenerated
     */
    public String getJgbh() {
        return jgbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_teacher_student.jgbh
     *
     * @param jgbh the value for stat_teacher_student.jgbh
     *
     * @mbggenerated
     */
    public void setJgbh(String jgbh) {
        this.jgbh = jgbh == null ? null : jgbh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_teacher_student.nf
     *
     * @return the value of stat_teacher_student.nf
     *
     * @mbggenerated
     */
    public String getNf() {
        return nf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_teacher_student.nf
     *
     * @param nf the value for stat_teacher_student.nf
     *
     * @mbggenerated
     */
    public void setNf(String nf) {
        this.nf = nf == null ? null : nf.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_teacher_student.bdrs
     *
     * @return the value of stat_teacher_student.bdrs
     *
     * @mbggenerated
     */
    public Integer getBdrs() {
        return bdrs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_teacher_student.bdrs
     *
     * @param bdrs the value for stat_teacher_student.bdrs
     *
     * @mbggenerated
     */
    public void setBdrs(Integer bdrs) {
        this.bdrs = bdrs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_teacher_student.bsrs
     *
     * @return the value of stat_teacher_student.bsrs
     *
     * @mbggenerated
     */
    public Integer getBsrs() {
        return bsrs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_teacher_student.bsrs
     *
     * @param bsrs the value for stat_teacher_student.bsrs
     *
     * @mbggenerated
     */
    public void setBsrs(Integer bsrs) {
        this.bsrs = bsrs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_teacher_student.sdrs
     *
     * @return the value of stat_teacher_student.sdrs
     *
     * @mbggenerated
     */
    public Integer getSdrs() {
        return sdrs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_teacher_student.sdrs
     *
     * @param sdrs the value for stat_teacher_student.sdrs
     *
     * @mbggenerated
     */
    public void setSdrs(Integer sdrs) {
        this.sdrs = sdrs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_teacher_student.ssrs
     *
     * @return the value of stat_teacher_student.ssrs
     *
     * @mbggenerated
     */
    public String getSsrs() {
        return ssrs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_teacher_student.ssrs
     *
     * @param ssrs the value for stat_teacher_student.ssrs
     *
     * @mbggenerated
     */
    public void setSsrs(String ssrs) {
        this.ssrs = ssrs == null ? null : ssrs.trim();
    }
}