package cn.arp.trend.entity.biz;

import java.util.Date;

public class StatPatentNew {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_patent_new.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_patent_new.jgbh
     *
     * @mbggenerated
     */
    private String jgbh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_patent_new.jgmc
     *
     * @mbggenerated
     */
    private String jgmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_patent_new.nf
     *
     * @mbggenerated
     */
    private String nf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_patent_new.zllx
     *
     * @mbggenerated
     */
    private String zllx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_patent_new.sq
     *
     * @mbggenerated
     */
    private Long sq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_patent_new.pz
     *
     * @mbggenerated
     */
    private Long pz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_patent_new.sx
     *
     * @mbggenerated
     */
    private Long sx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_patent_new.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_patent_new.id
     *
     * @return the value of stat_patent_new.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_patent_new.id
     *
     * @param id the value for stat_patent_new.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_patent_new.jgbh
     *
     * @return the value of stat_patent_new.jgbh
     *
     * @mbggenerated
     */
    public String getJgbh() {
        return jgbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_patent_new.jgbh
     *
     * @param jgbh the value for stat_patent_new.jgbh
     *
     * @mbggenerated
     */
    public void setJgbh(String jgbh) {
        this.jgbh = jgbh == null ? null : jgbh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_patent_new.jgmc
     *
     * @return the value of stat_patent_new.jgmc
     *
     * @mbggenerated
     */
    public String getJgmc() {
        return jgmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_patent_new.jgmc
     *
     * @param jgmc the value for stat_patent_new.jgmc
     *
     * @mbggenerated
     */
    public void setJgmc(String jgmc) {
        this.jgmc = jgmc == null ? null : jgmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_patent_new.nf
     *
     * @return the value of stat_patent_new.nf
     *
     * @mbggenerated
     */
    public String getNf() {
        return nf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_patent_new.nf
     *
     * @param nf the value for stat_patent_new.nf
     *
     * @mbggenerated
     */
    public void setNf(String nf) {
        this.nf = nf == null ? null : nf.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_patent_new.zllx
     *
     * @return the value of stat_patent_new.zllx
     *
     * @mbggenerated
     */
    public String getZllx() {
        return zllx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_patent_new.zllx
     *
     * @param zllx the value for stat_patent_new.zllx
     *
     * @mbggenerated
     */
    public void setZllx(String zllx) {
        this.zllx = zllx == null ? null : zllx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_patent_new.sq
     *
     * @return the value of stat_patent_new.sq
     *
     * @mbggenerated
     */
    public Long getSq() {
        return sq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_patent_new.sq
     *
     * @param sq the value for stat_patent_new.sq
     *
     * @mbggenerated
     */
    public void setSq(Long sq) {
        this.sq = sq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_patent_new.pz
     *
     * @return the value of stat_patent_new.pz
     *
     * @mbggenerated
     */
    public Long getPz() {
        return pz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_patent_new.pz
     *
     * @param pz the value for stat_patent_new.pz
     *
     * @mbggenerated
     */
    public void setPz(Long pz) {
        this.pz = pz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_patent_new.sx
     *
     * @return the value of stat_patent_new.sx
     *
     * @mbggenerated
     */
    public Long getSx() {
        return sx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_patent_new.sx
     *
     * @param sx the value for stat_patent_new.sx
     *
     * @mbggenerated
     */
    public void setSx(Long sx) {
        this.sx = sx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_patent_new.update_time
     *
     * @return the value of stat_patent_new.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_patent_new.update_time
     *
     * @param updateTime the value for stat_patent_new.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}