package cn.arp.trend.entity.biz;

public class StatXdzx {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_xdzx.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_xdzx.jgmc
     *
     * @mbggenerated
     */
    private String jgmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_xdzx.nf
     *
     * @mbggenerated
     */
    private String nf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_xdzx.xzxms
     *
     * @mbggenerated
     */
    private Long xzxms;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_xdzx.xzxm_zjf
     *
     * @mbggenerated
     */
    private Double xzxmZjf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_xdzx.a
     *
     * @mbggenerated
     */
    private Long a;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_xdzx.a_jf
     *
     * @mbggenerated
     */
    private Double aJf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_xdzx.b
     *
     * @mbggenerated
     */
    private Long b;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_xdzx.b_jf
     *
     * @mbggenerated
     */
    private Double bJf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_xdzx.zyxms
     *
     * @mbggenerated
     */
    private Long zyxms;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_xdzx.zyxm_zjf
     *
     * @mbggenerated
     */
    private Double zyxmZjf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_xdzx.a_zs
     *
     * @mbggenerated
     */
    private Long aZs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_xdzx.b_zs
     *
     * @mbggenerated
     */
    private Long bZs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_xdzx.a_zjf
     *
     * @mbggenerated
     */
    private Double aZjf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_xdzx.b_zjf
     *
     * @mbggenerated
     */
    private Double bZjf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_xdzx.datasource_type
     *
     * @mbggenerated
     */
    private String datasourceType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_xdzx.id
     *
     * @return the value of stat_xdzx.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_xdzx.id
     *
     * @param id the value for stat_xdzx.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_xdzx.jgmc
     *
     * @return the value of stat_xdzx.jgmc
     *
     * @mbggenerated
     */
    public String getJgmc() {
        return jgmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_xdzx.jgmc
     *
     * @param jgmc the value for stat_xdzx.jgmc
     *
     * @mbggenerated
     */
    public void setJgmc(String jgmc) {
        this.jgmc = jgmc == null ? null : jgmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_xdzx.nf
     *
     * @return the value of stat_xdzx.nf
     *
     * @mbggenerated
     */
    public String getNf() {
        return nf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_xdzx.nf
     *
     * @param nf the value for stat_xdzx.nf
     *
     * @mbggenerated
     */
    public void setNf(String nf) {
        this.nf = nf == null ? null : nf.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_xdzx.xzxms
     *
     * @return the value of stat_xdzx.xzxms
     *
     * @mbggenerated
     */
    public Long getXzxms() {
        return xzxms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_xdzx.xzxms
     *
     * @param xzxms the value for stat_xdzx.xzxms
     *
     * @mbggenerated
     */
    public void setXzxms(Long xzxms) {
        this.xzxms = xzxms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_xdzx.xzxm_zjf
     *
     * @return the value of stat_xdzx.xzxm_zjf
     *
     * @mbggenerated
     */
    public Double getXzxmZjf() {
        return xzxmZjf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_xdzx.xzxm_zjf
     *
     * @param xzxmZjf the value for stat_xdzx.xzxm_zjf
     *
     * @mbggenerated
     */
    public void setXzxmZjf(Double xzxmZjf) {
        this.xzxmZjf = xzxmZjf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_xdzx.a
     *
     * @return the value of stat_xdzx.a
     *
     * @mbggenerated
     */
    public Long getA() {
        return a;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_xdzx.a
     *
     * @param a the value for stat_xdzx.a
     *
     * @mbggenerated
     */
    public void setA(Long a) {
        this.a = a;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_xdzx.a_jf
     *
     * @return the value of stat_xdzx.a_jf
     *
     * @mbggenerated
     */
    public Double getaJf() {
        return aJf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_xdzx.a_jf
     *
     * @param aJf the value for stat_xdzx.a_jf
     *
     * @mbggenerated
     */
    public void setaJf(Double aJf) {
        this.aJf = aJf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_xdzx.b
     *
     * @return the value of stat_xdzx.b
     *
     * @mbggenerated
     */
    public Long getB() {
        return b;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_xdzx.b
     *
     * @param b the value for stat_xdzx.b
     *
     * @mbggenerated
     */
    public void setB(Long b) {
        this.b = b;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_xdzx.b_jf
     *
     * @return the value of stat_xdzx.b_jf
     *
     * @mbggenerated
     */
    public Double getbJf() {
        return bJf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_xdzx.b_jf
     *
     * @param bJf the value for stat_xdzx.b_jf
     *
     * @mbggenerated
     */
    public void setbJf(Double bJf) {
        this.bJf = bJf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_xdzx.zyxms
     *
     * @return the value of stat_xdzx.zyxms
     *
     * @mbggenerated
     */
    public Long getZyxms() {
        return zyxms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_xdzx.zyxms
     *
     * @param zyxms the value for stat_xdzx.zyxms
     *
     * @mbggenerated
     */
    public void setZyxms(Long zyxms) {
        this.zyxms = zyxms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_xdzx.zyxm_zjf
     *
     * @return the value of stat_xdzx.zyxm_zjf
     *
     * @mbggenerated
     */
    public Double getZyxmZjf() {
        return zyxmZjf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_xdzx.zyxm_zjf
     *
     * @param zyxmZjf the value for stat_xdzx.zyxm_zjf
     *
     * @mbggenerated
     */
    public void setZyxmZjf(Double zyxmZjf) {
        this.zyxmZjf = zyxmZjf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_xdzx.a_zs
     *
     * @return the value of stat_xdzx.a_zs
     *
     * @mbggenerated
     */
    public Long getaZs() {
        return aZs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_xdzx.a_zs
     *
     * @param aZs the value for stat_xdzx.a_zs
     *
     * @mbggenerated
     */
    public void setaZs(Long aZs) {
        this.aZs = aZs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_xdzx.b_zs
     *
     * @return the value of stat_xdzx.b_zs
     *
     * @mbggenerated
     */
    public Long getbZs() {
        return bZs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_xdzx.b_zs
     *
     * @param bZs the value for stat_xdzx.b_zs
     *
     * @mbggenerated
     */
    public void setbZs(Long bZs) {
        this.bZs = bZs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_xdzx.a_zjf
     *
     * @return the value of stat_xdzx.a_zjf
     *
     * @mbggenerated
     */
    public Double getaZjf() {
        return aZjf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_xdzx.a_zjf
     *
     * @param aZjf the value for stat_xdzx.a_zjf
     *
     * @mbggenerated
     */
    public void setaZjf(Double aZjf) {
        this.aZjf = aZjf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_xdzx.b_zjf
     *
     * @return the value of stat_xdzx.b_zjf
     *
     * @mbggenerated
     */
    public Double getbZjf() {
        return bZjf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_xdzx.b_zjf
     *
     * @param bZjf the value for stat_xdzx.b_zjf
     *
     * @mbggenerated
     */
    public void setbZjf(Double bZjf) {
        this.bZjf = bZjf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_xdzx.datasource_type
     *
     * @return the value of stat_xdzx.datasource_type
     *
     * @mbggenerated
     */
    public String getDatasourceType() {
        return datasourceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_xdzx.datasource_type
     *
     * @param datasourceType the value for stat_xdzx.datasource_type
     *
     * @mbggenerated
     */
    public void setDatasourceType(String datasourceType) {
        this.datasourceType = datasourceType == null ? null : datasourceType.trim();
    }
}