package cn.arp.trend.entity.biz;

public class StatCasStaffQianzaiyearcountBydanweiKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_cas_staff_qianzaiyearcount_bydanwei.year
     *
     * @mbggenerated
     */
    private Long year;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_cas_staff_qianzaiyearcount_bydanwei.jgbh
     *
     * @mbggenerated
     */
    private String jgbh;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_cas_staff_qianzaiyearcount_bydanwei.year
     *
     * @return the value of stat_cas_staff_qianzaiyearcount_bydanwei.year
     *
     * @mbggenerated
     */
    public Long getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_cas_staff_qianzaiyearcount_bydanwei.year
     *
     * @param year the value for stat_cas_staff_qianzaiyearcount_bydanwei.year
     *
     * @mbggenerated
     */
    public void setYear(Long year) {
        this.year = year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_cas_staff_qianzaiyearcount_bydanwei.jgbh
     *
     * @return the value of stat_cas_staff_qianzaiyearcount_bydanwei.jgbh
     *
     * @mbggenerated
     */
    public String getJgbh() {
        return jgbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_cas_staff_qianzaiyearcount_bydanwei.jgbh
     *
     * @param jgbh the value for stat_cas_staff_qianzaiyearcount_bydanwei.jgbh
     *
     * @mbggenerated
     */
    public void setJgbh(String jgbh) {
        this.jgbh = jgbh == null ? null : jgbh.trim();
    }
}