package cn.arp.trend.entity.biz;

import java.math.BigDecimal;
import java.util.Date;

public class StatArpFinBudgetExecute {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_arp_fin_budget_execute.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_arp_fin_budget_execute.jgbh
     *
     * @mbggenerated
     */
    private String jgbh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_arp_fin_budget_execute.jgmc
     *
     * @mbggenerated
     */
    private String jgmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_arp_fin_budget_execute.nf
     *
     * @mbggenerated
     */
    private String nf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_arp_fin_budget_execute.yf
     *
     * @mbggenerated
     */
    private String yf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_arp_fin_budget_execute.czbk
     *
     * @mbggenerated
     */
    private BigDecimal czbk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_arp_fin_budget_execute.zcje
     *
     * @mbggenerated
     */
    private BigDecimal zcje;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_arp_fin_budget_execute.wcl
     *
     * @mbggenerated
     */
    private BigDecimal wcl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_arp_fin_budget_execute.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_arp_fin_budget_execute.id
     *
     * @return the value of stat_arp_fin_budget_execute.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_arp_fin_budget_execute.id
     *
     * @param id the value for stat_arp_fin_budget_execute.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_arp_fin_budget_execute.jgbh
     *
     * @return the value of stat_arp_fin_budget_execute.jgbh
     *
     * @mbggenerated
     */
    public String getJgbh() {
        return jgbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_arp_fin_budget_execute.jgbh
     *
     * @param jgbh the value for stat_arp_fin_budget_execute.jgbh
     *
     * @mbggenerated
     */
    public void setJgbh(String jgbh) {
        this.jgbh = jgbh == null ? null : jgbh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_arp_fin_budget_execute.jgmc
     *
     * @return the value of stat_arp_fin_budget_execute.jgmc
     *
     * @mbggenerated
     */
    public String getJgmc() {
        return jgmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_arp_fin_budget_execute.jgmc
     *
     * @param jgmc the value for stat_arp_fin_budget_execute.jgmc
     *
     * @mbggenerated
     */
    public void setJgmc(String jgmc) {
        this.jgmc = jgmc == null ? null : jgmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_arp_fin_budget_execute.nf
     *
     * @return the value of stat_arp_fin_budget_execute.nf
     *
     * @mbggenerated
     */
    public String getNf() {
        return nf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_arp_fin_budget_execute.nf
     *
     * @param nf the value for stat_arp_fin_budget_execute.nf
     *
     * @mbggenerated
     */
    public void setNf(String nf) {
        this.nf = nf == null ? null : nf.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_arp_fin_budget_execute.yf
     *
     * @return the value of stat_arp_fin_budget_execute.yf
     *
     * @mbggenerated
     */
    public String getYf() {
        return yf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_arp_fin_budget_execute.yf
     *
     * @param yf the value for stat_arp_fin_budget_execute.yf
     *
     * @mbggenerated
     */
    public void setYf(String yf) {
        this.yf = yf == null ? null : yf.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_arp_fin_budget_execute.czbk
     *
     * @return the value of stat_arp_fin_budget_execute.czbk
     *
     * @mbggenerated
     */
    public BigDecimal getCzbk() {
        return czbk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_arp_fin_budget_execute.czbk
     *
     * @param czbk the value for stat_arp_fin_budget_execute.czbk
     *
     * @mbggenerated
     */
    public void setCzbk(BigDecimal czbk) {
        this.czbk = czbk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_arp_fin_budget_execute.zcje
     *
     * @return the value of stat_arp_fin_budget_execute.zcje
     *
     * @mbggenerated
     */
    public BigDecimal getZcje() {
        return zcje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_arp_fin_budget_execute.zcje
     *
     * @param zcje the value for stat_arp_fin_budget_execute.zcje
     *
     * @mbggenerated
     */
    public void setZcje(BigDecimal zcje) {
        this.zcje = zcje;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_arp_fin_budget_execute.wcl
     *
     * @return the value of stat_arp_fin_budget_execute.wcl
     *
     * @mbggenerated
     */
    public BigDecimal getWcl() {
        return wcl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_arp_fin_budget_execute.wcl
     *
     * @param wcl the value for stat_arp_fin_budget_execute.wcl
     *
     * @mbggenerated
     */
    public void setWcl(BigDecimal wcl) {
        this.wcl = wcl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_arp_fin_budget_execute.update_time
     *
     * @return the value of stat_arp_fin_budget_execute.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_arp_fin_budget_execute.update_time
     *
     * @param updateTime the value for stat_arp_fin_budget_execute.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}