package cn.arp.trend.entity.biz;

public class StatHcauthorsCount {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_hcauthors_count.total
     *
     * @mbggenerated
     */
    private Integer total;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_hcauthors_count.nf
     *
     * @mbggenerated
     */
    private String nf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_hcauthors_count.category_ch
     *
     * @mbggenerated
     */
    private String categoryCh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_hcauthors_count.institution_ch
     *
     * @mbggenerated
     */
    private String institutionCh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_hcauthors_count.country_ch
     *
     * @mbggenerated
     */
    private String countryCh;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_hcauthors_count.total
     *
     * @return the value of stat_hcauthors_count.total
     *
     * @mbggenerated
     */
    public Integer getTotal() {
        return total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_hcauthors_count.total
     *
     * @param total the value for stat_hcauthors_count.total
     *
     * @mbggenerated
     */
    public void setTotal(Integer total) {
        this.total = total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_hcauthors_count.nf
     *
     * @return the value of stat_hcauthors_count.nf
     *
     * @mbggenerated
     */
    public String getNf() {
        return nf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_hcauthors_count.nf
     *
     * @param nf the value for stat_hcauthors_count.nf
     *
     * @mbggenerated
     */
    public void setNf(String nf) {
        this.nf = nf == null ? null : nf.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_hcauthors_count.category_ch
     *
     * @return the value of stat_hcauthors_count.category_ch
     *
     * @mbggenerated
     */
    public String getCategoryCh() {
        return categoryCh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_hcauthors_count.category_ch
     *
     * @param categoryCh the value for stat_hcauthors_count.category_ch
     *
     * @mbggenerated
     */
    public void setCategoryCh(String categoryCh) {
        this.categoryCh = categoryCh == null ? null : categoryCh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_hcauthors_count.institution_ch
     *
     * @return the value of stat_hcauthors_count.institution_ch
     *
     * @mbggenerated
     */
    public String getInstitutionCh() {
        return institutionCh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_hcauthors_count.institution_ch
     *
     * @param institutionCh the value for stat_hcauthors_count.institution_ch
     *
     * @mbggenerated
     */
    public void setInstitutionCh(String institutionCh) {
        this.institutionCh = institutionCh == null ? null : institutionCh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_hcauthors_count.country_ch
     *
     * @return the value of stat_hcauthors_count.country_ch
     *
     * @mbggenerated
     */
    public String getCountryCh() {
        return countryCh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_hcauthors_count.country_ch
     *
     * @param countryCh the value for stat_hcauthors_count.country_ch
     *
     * @mbggenerated
     */
    public void setCountryCh(String countryCh) {
        this.countryCh = countryCh == null ? null : countryCh.trim();
    }
}