package cn.arp.trend.entity.biz;

public class StatPatent {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_patent.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_patent.jgmc
     *
     * @mbggenerated
     */
    private String jgmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_patent.nf
     *
     * @mbggenerated
     */
    private String nf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_patent.zllx
     *
     * @mbggenerated
     */
    private String zllx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_patent.ssly
     *
     * @mbggenerated
     */
    private String ssly;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_patent.lj
     *
     * @mbggenerated
     */
    private Long lj;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_patent.xz
     *
     * @mbggenerated
     */
    private Long xz;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_patent.sx
     *
     * @mbggenerated
     */
    private Long sx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_patent.yx
     *
     * @mbggenerated
     */
    private Long yx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_patent.datasource_type
     *
     * @mbggenerated
     */
    private String datasourceType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_patent.id
     *
     * @return the value of stat_patent.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_patent.id
     *
     * @param id the value for stat_patent.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_patent.jgmc
     *
     * @return the value of stat_patent.jgmc
     *
     * @mbggenerated
     */
    public String getJgmc() {
        return jgmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_patent.jgmc
     *
     * @param jgmc the value for stat_patent.jgmc
     *
     * @mbggenerated
     */
    public void setJgmc(String jgmc) {
        this.jgmc = jgmc == null ? null : jgmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_patent.nf
     *
     * @return the value of stat_patent.nf
     *
     * @mbggenerated
     */
    public String getNf() {
        return nf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_patent.nf
     *
     * @param nf the value for stat_patent.nf
     *
     * @mbggenerated
     */
    public void setNf(String nf) {
        this.nf = nf == null ? null : nf.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_patent.zllx
     *
     * @return the value of stat_patent.zllx
     *
     * @mbggenerated
     */
    public String getZllx() {
        return zllx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_patent.zllx
     *
     * @param zllx the value for stat_patent.zllx
     *
     * @mbggenerated
     */
    public void setZllx(String zllx) {
        this.zllx = zllx == null ? null : zllx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_patent.ssly
     *
     * @return the value of stat_patent.ssly
     *
     * @mbggenerated
     */
    public String getSsly() {
        return ssly;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_patent.ssly
     *
     * @param ssly the value for stat_patent.ssly
     *
     * @mbggenerated
     */
    public void setSsly(String ssly) {
        this.ssly = ssly == null ? null : ssly.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_patent.lj
     *
     * @return the value of stat_patent.lj
     *
     * @mbggenerated
     */
    public Long getLj() {
        return lj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_patent.lj
     *
     * @param lj the value for stat_patent.lj
     *
     * @mbggenerated
     */
    public void setLj(Long lj) {
        this.lj = lj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_patent.xz
     *
     * @return the value of stat_patent.xz
     *
     * @mbggenerated
     */
    public Long getXz() {
        return xz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_patent.xz
     *
     * @param xz the value for stat_patent.xz
     *
     * @mbggenerated
     */
    public void setXz(Long xz) {
        this.xz = xz;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_patent.sx
     *
     * @return the value of stat_patent.sx
     *
     * @mbggenerated
     */
    public Long getSx() {
        return sx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_patent.sx
     *
     * @param sx the value for stat_patent.sx
     *
     * @mbggenerated
     */
    public void setSx(Long sx) {
        this.sx = sx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_patent.yx
     *
     * @return the value of stat_patent.yx
     *
     * @mbggenerated
     */
    public Long getYx() {
        return yx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_patent.yx
     *
     * @param yx the value for stat_patent.yx
     *
     * @mbggenerated
     */
    public void setYx(Long yx) {
        this.yx = yx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_patent.datasource_type
     *
     * @return the value of stat_patent.datasource_type
     *
     * @mbggenerated
     */
    public String getDatasourceType() {
        return datasourceType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_patent.datasource_type
     *
     * @param datasourceType the value for stat_patent.datasource_type
     *
     * @mbggenerated
     */
    public void setDatasourceType(String datasourceType) {
        this.datasourceType = datasourceType == null ? null : datasourceType.trim();
    }
}