package cn.arp.trend.entity.biz;

import java.util.Date;

public class StatArpFinAsset {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_arp_fin_asset.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_arp_fin_asset.jgbh
     *
     * @mbggenerated
     */
    private String jgbh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_arp_fin_asset.jgmc
     *
     * @mbggenerated
     */
    private String jgmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_arp_fin_asset.nf
     *
     * @mbggenerated
     */
    private String nf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_arp_fin_asset.zzc
     *
     * @mbggenerated
     */
    private Double zzc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_arp_fin_asset.zxl
     *
     * @mbggenerated
     */
    private Double zxl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_arp_fin_asset.zc
     *
     * @mbggenerated
     */
    private Double zc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_arp_fin_asset.sr
     *
     * @mbggenerated
     */
    private Double sr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_arp_fin_asset.ye
     *
     * @mbggenerated
     */
    private Double ye;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_arp_fin_asset.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_arp_fin_asset.id
     *
     * @return the value of stat_arp_fin_asset.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_arp_fin_asset.id
     *
     * @param id the value for stat_arp_fin_asset.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_arp_fin_asset.jgbh
     *
     * @return the value of stat_arp_fin_asset.jgbh
     *
     * @mbggenerated
     */
    public String getJgbh() {
        return jgbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_arp_fin_asset.jgbh
     *
     * @param jgbh the value for stat_arp_fin_asset.jgbh
     *
     * @mbggenerated
     */
    public void setJgbh(String jgbh) {
        this.jgbh = jgbh == null ? null : jgbh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_arp_fin_asset.jgmc
     *
     * @return the value of stat_arp_fin_asset.jgmc
     *
     * @mbggenerated
     */
    public String getJgmc() {
        return jgmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_arp_fin_asset.jgmc
     *
     * @param jgmc the value for stat_arp_fin_asset.jgmc
     *
     * @mbggenerated
     */
    public void setJgmc(String jgmc) {
        this.jgmc = jgmc == null ? null : jgmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_arp_fin_asset.nf
     *
     * @return the value of stat_arp_fin_asset.nf
     *
     * @mbggenerated
     */
    public String getNf() {
        return nf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_arp_fin_asset.nf
     *
     * @param nf the value for stat_arp_fin_asset.nf
     *
     * @mbggenerated
     */
    public void setNf(String nf) {
        this.nf = nf == null ? null : nf.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_arp_fin_asset.zzc
     *
     * @return the value of stat_arp_fin_asset.zzc
     *
     * @mbggenerated
     */
    public Double getZzc() {
        return zzc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_arp_fin_asset.zzc
     *
     * @param zzc the value for stat_arp_fin_asset.zzc
     *
     * @mbggenerated
     */
    public void setZzc(Double zzc) {
        this.zzc = zzc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_arp_fin_asset.zxl
     *
     * @return the value of stat_arp_fin_asset.zxl
     *
     * @mbggenerated
     */
    public Double getZxl() {
        return zxl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_arp_fin_asset.zxl
     *
     * @param zxl the value for stat_arp_fin_asset.zxl
     *
     * @mbggenerated
     */
    public void setZxl(Double zxl) {
        this.zxl = zxl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_arp_fin_asset.zc
     *
     * @return the value of stat_arp_fin_asset.zc
     *
     * @mbggenerated
     */
    public Double getZc() {
        return zc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_arp_fin_asset.zc
     *
     * @param zc the value for stat_arp_fin_asset.zc
     *
     * @mbggenerated
     */
    public void setZc(Double zc) {
        this.zc = zc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_arp_fin_asset.sr
     *
     * @return the value of stat_arp_fin_asset.sr
     *
     * @mbggenerated
     */
    public Double getSr() {
        return sr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_arp_fin_asset.sr
     *
     * @param sr the value for stat_arp_fin_asset.sr
     *
     * @mbggenerated
     */
    public void setSr(Double sr) {
        this.sr = sr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_arp_fin_asset.ye
     *
     * @return the value of stat_arp_fin_asset.ye
     *
     * @mbggenerated
     */
    public Double getYe() {
        return ye;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_arp_fin_asset.ye
     *
     * @param ye the value for stat_arp_fin_asset.ye
     *
     * @mbggenerated
     */
    public void setYe(Double ye) {
        this.ye = ye;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_arp_fin_asset.update_time
     *
     * @return the value of stat_arp_fin_asset.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_arp_fin_asset.update_time
     *
     * @param updateTime the value for stat_arp_fin_asset.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}