package cn.arp.trend.entity.biz;

import java.util.Date;

public class StatArpStaff {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_arp_staff.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_arp_staff.jgbh
     *
     * @mbggenerated
     */
    private String jgbh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_arp_staff.jgmc
     *
     * @mbggenerated
     */
    private String jgmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_arp_staff.nf
     *
     * @mbggenerated
     */
    private String nf;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_arp_staff.zb
     *
     * @mbggenerated
     */
    private Integer zb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_arp_staff.ld
     *
     * @mbggenerated
     */
    private Integer ld;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_arp_staff.tx
     *
     * @mbggenerated
     */
    private Integer tx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stat_arp_staff.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_arp_staff.id
     *
     * @return the value of stat_arp_staff.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_arp_staff.id
     *
     * @param id the value for stat_arp_staff.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_arp_staff.jgbh
     *
     * @return the value of stat_arp_staff.jgbh
     *
     * @mbggenerated
     */
    public String getJgbh() {
        return jgbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_arp_staff.jgbh
     *
     * @param jgbh the value for stat_arp_staff.jgbh
     *
     * @mbggenerated
     */
    public void setJgbh(String jgbh) {
        this.jgbh = jgbh == null ? null : jgbh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_arp_staff.jgmc
     *
     * @return the value of stat_arp_staff.jgmc
     *
     * @mbggenerated
     */
    public String getJgmc() {
        return jgmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_arp_staff.jgmc
     *
     * @param jgmc the value for stat_arp_staff.jgmc
     *
     * @mbggenerated
     */
    public void setJgmc(String jgmc) {
        this.jgmc = jgmc == null ? null : jgmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_arp_staff.nf
     *
     * @return the value of stat_arp_staff.nf
     *
     * @mbggenerated
     */
    public String getNf() {
        return nf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_arp_staff.nf
     *
     * @param nf the value for stat_arp_staff.nf
     *
     * @mbggenerated
     */
    public void setNf(String nf) {
        this.nf = nf == null ? null : nf.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_arp_staff.zb
     *
     * @return the value of stat_arp_staff.zb
     *
     * @mbggenerated
     */
    public Integer getZb() {
        return zb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_arp_staff.zb
     *
     * @param zb the value for stat_arp_staff.zb
     *
     * @mbggenerated
     */
    public void setZb(Integer zb) {
        this.zb = zb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_arp_staff.ld
     *
     * @return the value of stat_arp_staff.ld
     *
     * @mbggenerated
     */
    public Integer getLd() {
        return ld;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_arp_staff.ld
     *
     * @param ld the value for stat_arp_staff.ld
     *
     * @mbggenerated
     */
    public void setLd(Integer ld) {
        this.ld = ld;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_arp_staff.tx
     *
     * @return the value of stat_arp_staff.tx
     *
     * @mbggenerated
     */
    public Integer getTx() {
        return tx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_arp_staff.tx
     *
     * @param tx the value for stat_arp_staff.tx
     *
     * @mbggenerated
     */
    public void setTx(Integer tx) {
        this.tx = tx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stat_arp_staff.update_time
     *
     * @return the value of stat_arp_staff.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stat_arp_staff.update_time
     *
     * @param updateTime the value for stat_arp_staff.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}