package cn.arp.trend.entity.biz;

public class TempCasStaffForRencaicount {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp_cas_staff_for_rencaicount.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp_cas_staff_for_rencaicount.xm
     *
     * @mbggenerated
     */
    private String xm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp_cas_staff_for_rencaicount.xb
     *
     * @mbggenerated
     */
    private String xb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp_cas_staff_for_rencaicount.jgbh
     *
     * @mbggenerated
     */
    private String jgbh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp_cas_staff_for_rencaicount.jgmc
     *
     * @mbggenerated
     */
    private String jgmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp_cas_staff_for_rencaicount.zwmc
     *
     * @mbggenerated
     */
    private String zwmc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp_cas_staff_for_rencaicount.csrq
     *
     * @mbggenerated
     */
    private String csrq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp_cas_staff_for_rencaicount.xmp1
     *
     * @mbggenerated
     */
    private String xmp1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp_cas_staff_for_rencaicount.jgmcp1
     *
     * @mbggenerated
     */
    private String jgmcp1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column temp_cas_staff_for_rencaicount.xw
     *
     * @mbggenerated
     */
    private String xw;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp_cas_staff_for_rencaicount.id
     *
     * @return the value of temp_cas_staff_for_rencaicount.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp_cas_staff_for_rencaicount.id
     *
     * @param id the value for temp_cas_staff_for_rencaicount.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp_cas_staff_for_rencaicount.xm
     *
     * @return the value of temp_cas_staff_for_rencaicount.xm
     *
     * @mbggenerated
     */
    public String getXm() {
        return xm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp_cas_staff_for_rencaicount.xm
     *
     * @param xm the value for temp_cas_staff_for_rencaicount.xm
     *
     * @mbggenerated
     */
    public void setXm(String xm) {
        this.xm = xm == null ? null : xm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp_cas_staff_for_rencaicount.xb
     *
     * @return the value of temp_cas_staff_for_rencaicount.xb
     *
     * @mbggenerated
     */
    public String getXb() {
        return xb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp_cas_staff_for_rencaicount.xb
     *
     * @param xb the value for temp_cas_staff_for_rencaicount.xb
     *
     * @mbggenerated
     */
    public void setXb(String xb) {
        this.xb = xb == null ? null : xb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp_cas_staff_for_rencaicount.jgbh
     *
     * @return the value of temp_cas_staff_for_rencaicount.jgbh
     *
     * @mbggenerated
     */
    public String getJgbh() {
        return jgbh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp_cas_staff_for_rencaicount.jgbh
     *
     * @param jgbh the value for temp_cas_staff_for_rencaicount.jgbh
     *
     * @mbggenerated
     */
    public void setJgbh(String jgbh) {
        this.jgbh = jgbh == null ? null : jgbh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp_cas_staff_for_rencaicount.jgmc
     *
     * @return the value of temp_cas_staff_for_rencaicount.jgmc
     *
     * @mbggenerated
     */
    public String getJgmc() {
        return jgmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp_cas_staff_for_rencaicount.jgmc
     *
     * @param jgmc the value for temp_cas_staff_for_rencaicount.jgmc
     *
     * @mbggenerated
     */
    public void setJgmc(String jgmc) {
        this.jgmc = jgmc == null ? null : jgmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp_cas_staff_for_rencaicount.zwmc
     *
     * @return the value of temp_cas_staff_for_rencaicount.zwmc
     *
     * @mbggenerated
     */
    public String getZwmc() {
        return zwmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp_cas_staff_for_rencaicount.zwmc
     *
     * @param zwmc the value for temp_cas_staff_for_rencaicount.zwmc
     *
     * @mbggenerated
     */
    public void setZwmc(String zwmc) {
        this.zwmc = zwmc == null ? null : zwmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp_cas_staff_for_rencaicount.csrq
     *
     * @return the value of temp_cas_staff_for_rencaicount.csrq
     *
     * @mbggenerated
     */
    public String getCsrq() {
        return csrq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp_cas_staff_for_rencaicount.csrq
     *
     * @param csrq the value for temp_cas_staff_for_rencaicount.csrq
     *
     * @mbggenerated
     */
    public void setCsrq(String csrq) {
        this.csrq = csrq == null ? null : csrq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp_cas_staff_for_rencaicount.xmp1
     *
     * @return the value of temp_cas_staff_for_rencaicount.xmp1
     *
     * @mbggenerated
     */
    public String getXmp1() {
        return xmp1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp_cas_staff_for_rencaicount.xmp1
     *
     * @param xmp1 the value for temp_cas_staff_for_rencaicount.xmp1
     *
     * @mbggenerated
     */
    public void setXmp1(String xmp1) {
        this.xmp1 = xmp1 == null ? null : xmp1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp_cas_staff_for_rencaicount.jgmcp1
     *
     * @return the value of temp_cas_staff_for_rencaicount.jgmcp1
     *
     * @mbggenerated
     */
    public String getJgmcp1() {
        return jgmcp1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp_cas_staff_for_rencaicount.jgmcp1
     *
     * @param jgmcp1 the value for temp_cas_staff_for_rencaicount.jgmcp1
     *
     * @mbggenerated
     */
    public void setJgmcp1(String jgmcp1) {
        this.jgmcp1 = jgmcp1 == null ? null : jgmcp1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column temp_cas_staff_for_rencaicount.xw
     *
     * @return the value of temp_cas_staff_for_rencaicount.xw
     *
     * @mbggenerated
     */
    public String getXw() {
        return xw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column temp_cas_staff_for_rencaicount.xw
     *
     * @param xw the value for temp_cas_staff_for_rencaicount.xw
     *
     * @mbggenerated
     */
    public void setXw(String xw) {
        this.xw = xw == null ? null : xw.trim();
    }
}