package cn.arp.trend.entity.biz;

public class UpdateFrequency {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column update_frequency.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column update_frequency.module_name
     *
     * @mbggenerated
     */
    private String moduleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column update_frequency.page_level
     *
     * @mbggenerated
     */
    private String pageLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column update_frequency.sub_module_name
     *
     * @mbggenerated
     */
    private String subModuleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column update_frequency.graph_name
     *
     * @mbggenerated
     */
    private String graphName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column update_frequency.data_key
     *
     * @mbggenerated
     */
    private String dataKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column update_frequency.data_value
     *
     * @mbggenerated
     */
    private String dataValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column update_frequency.frequency
     *
     * @mbggenerated
     */
    private String frequency;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column update_frequency.notes
     *
     * @mbggenerated
     */
    private String notes;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column update_frequency.id
     *
     * @return the value of update_frequency.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column update_frequency.id
     *
     * @param id the value for update_frequency.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column update_frequency.module_name
     *
     * @return the value of update_frequency.module_name
     *
     * @mbggenerated
     */
    public String getModuleName() {
        return moduleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column update_frequency.module_name
     *
     * @param moduleName the value for update_frequency.module_name
     *
     * @mbggenerated
     */
    public void setModuleName(String moduleName) {
        this.moduleName = moduleName == null ? null : moduleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column update_frequency.page_level
     *
     * @return the value of update_frequency.page_level
     *
     * @mbggenerated
     */
    public String getPageLevel() {
        return pageLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column update_frequency.page_level
     *
     * @param pageLevel the value for update_frequency.page_level
     *
     * @mbggenerated
     */
    public void setPageLevel(String pageLevel) {
        this.pageLevel = pageLevel == null ? null : pageLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column update_frequency.sub_module_name
     *
     * @return the value of update_frequency.sub_module_name
     *
     * @mbggenerated
     */
    public String getSubModuleName() {
        return subModuleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column update_frequency.sub_module_name
     *
     * @param subModuleName the value for update_frequency.sub_module_name
     *
     * @mbggenerated
     */
    public void setSubModuleName(String subModuleName) {
        this.subModuleName = subModuleName == null ? null : subModuleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column update_frequency.graph_name
     *
     * @return the value of update_frequency.graph_name
     *
     * @mbggenerated
     */
    public String getGraphName() {
        return graphName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column update_frequency.graph_name
     *
     * @param graphName the value for update_frequency.graph_name
     *
     * @mbggenerated
     */
    public void setGraphName(String graphName) {
        this.graphName = graphName == null ? null : graphName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column update_frequency.data_key
     *
     * @return the value of update_frequency.data_key
     *
     * @mbggenerated
     */
    public String getDataKey() {
        return dataKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column update_frequency.data_key
     *
     * @param dataKey the value for update_frequency.data_key
     *
     * @mbggenerated
     */
    public void setDataKey(String dataKey) {
        this.dataKey = dataKey == null ? null : dataKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column update_frequency.data_value
     *
     * @return the value of update_frequency.data_value
     *
     * @mbggenerated
     */
    public String getDataValue() {
        return dataValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column update_frequency.data_value
     *
     * @param dataValue the value for update_frequency.data_value
     *
     * @mbggenerated
     */
    public void setDataValue(String dataValue) {
        this.dataValue = dataValue == null ? null : dataValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column update_frequency.frequency
     *
     * @return the value of update_frequency.frequency
     *
     * @mbggenerated
     */
    public String getFrequency() {
        return frequency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column update_frequency.frequency
     *
     * @param frequency the value for update_frequency.frequency
     *
     * @mbggenerated
     */
    public void setFrequency(String frequency) {
        this.frequency = frequency == null ? null : frequency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column update_frequency.notes
     *
     * @return the value of update_frequency.notes
     *
     * @mbggenerated
     */
    public String getNotes() {
        return notes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column update_frequency.notes
     *
     * @param notes the value for update_frequency.notes
     *
     * @mbggenerated
     */
    public void setNotes(String notes) {
        this.notes = notes == null ? null : notes.trim();
    }
}