package cn.arp.trend.repository.biz.auto;

import cn.arp.trend.entity.biz.CasAcademicianChina;

public interface CasAcademicianChinaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cas_academician_china
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cas_academician_china
     *
     * @mbggenerated
     */
    int insert(CasAcademicianChina record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cas_academician_china
     *
     * @mbggenerated
     */
    int insertSelective(CasAcademicianChina record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cas_academician_china
     *
     * @mbggenerated
     */
    CasAcademicianChina selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cas_academician_china
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CasAcademicianChina record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cas_academician_china
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CasAcademicianChina record);
}