package cn.arp.trend.repository.biz.auto;

import cn.arp.trend.entity.biz.CasAcademicianCaeChina;

public interface CasAcademicianCaeChinaMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cas_academician_cae_china
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cas_academician_cae_china
     *
     * @mbggenerated
     */
    int insert(CasAcademicianCaeChina record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cas_academician_cae_china
     *
     * @mbggenerated
     */
    int insertSelective(CasAcademicianCaeChina record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cas_academician_cae_china
     *
     * @mbggenerated
     */
    CasAcademicianCaeChina selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cas_academician_cae_china
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CasAcademicianCaeChina record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cas_academician_cae_china
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CasAcademicianCaeChina record);
}