package cn.arp.trend.repository.biz.auto;

import cn.arp.trend.entity.biz.CasAcademicianForeign;

public interface CasAcademicianForeignMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cas_academician_foreign
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cas_academician_foreign
     *
     * @mbggenerated
     */
    int insert(CasAcademicianForeign record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cas_academician_foreign
     *
     * @mbggenerated
     */
    int insertSelective(CasAcademicianForeign record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cas_academician_foreign
     *
     * @mbggenerated
     */
    CasAcademicianForeign selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cas_academician_foreign
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CasAcademicianForeign record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cas_academician_foreign
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CasAcademicianForeign record);
}