package cn.arp.trend.repository.biz.auto;

import cn.arp.trend.entity.biz.CasChinaAward10YearFinal;
import cn.arp.trend.entity.biz.CasChinaAward10YearFinalWithBLOBs;

public interface CasChinaAward10YearFinalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cas_china_award_10year_final
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cas_china_award_10year_final
     *
     * @mbggenerated
     */
    int insert(CasChinaAward10YearFinalWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cas_china_award_10year_final
     *
     * @mbggenerated
     */
    int insertSelective(CasChinaAward10YearFinalWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cas_china_award_10year_final
     *
     * @mbggenerated
     */
    CasChinaAward10YearFinalWithBLOBs selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cas_china_award_10year_final
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CasChinaAward10YearFinalWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cas_china_award_10year_final
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(CasChinaAward10YearFinalWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cas_china_award_10year_final
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CasChinaAward10YearFinal record);
}