package cn.arp.trend.repository.biz.auto;

import cn.arp.trend.entity.biz.CasEduFTeacherInfo;

public interface CasEduFTeacherInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cas_edu_f_teacher_info
     *
     * @mbggenerated
     */
    int insert(CasEduFTeacherInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cas_edu_f_teacher_info
     *
     * @mbggenerated
     */
    int insertSelective(CasEduFTeacherInfo record);
}