package cn.arp.trend.repository.biz.auto;

import cn.arp.trend.entity.biz.CasHlhlAwardWinner;

public interface CasHlhlAwardWinnerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cas_hlhl_award_winner
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cas_hlhl_award_winner
     *
     * @mbggenerated
     */
    int insert(CasHlhlAwardWinner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cas_hlhl_award_winner
     *
     * @mbggenerated
     */
    int insertSelective(CasHlhlAwardWinner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cas_hlhl_award_winner
     *
     * @mbggenerated
     */
    CasHlhlAwardWinner selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cas_hlhl_award_winner
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CasHlhlAwardWinner record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cas_hlhl_award_winner
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CasHlhlAwardWinner record);
}