package cn.arp.trend.repository.biz.auto;

import cn.arp.trend.entity.biz.CasNo1IrcPm14;

public interface CasNo1IrcPm14Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cas_no1_irc_pm_14
     *
     * @mbggenerated
     */
    int insert(CasNo1IrcPm14 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cas_no1_irc_pm_14
     *
     * @mbggenerated
     */
    int insertSelective(CasNo1IrcPm14 record);
}