package cn.arp.trend.repository.biz.auto;

import cn.arp.trend.entity.biz.CasPxxJcptCdsysXwPxLwKxjFmjJbj;

public interface CasPxxJcptCdsysXwPxLwKxjFmjJbjMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cas_pxx_jcpt_cdsys_xw_px_lw_kxj_fmj_jbj
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cas_pxx_jcpt_cdsys_xw_px_lw_kxj_fmj_jbj
     *
     * @mbggenerated
     */
    int insert(CasPxxJcptCdsysXwPxLwKxjFmjJbj record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cas_pxx_jcpt_cdsys_xw_px_lw_kxj_fmj_jbj
     *
     * @mbggenerated
     */
    int insertSelective(CasPxxJcptCdsysXwPxLwKxjFmjJbj record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cas_pxx_jcpt_cdsys_xw_px_lw_kxj_fmj_jbj
     *
     * @mbggenerated
     */
    CasPxxJcptCdsysXwPxLwKxjFmjJbj selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cas_pxx_jcpt_cdsys_xw_px_lw_kxj_fmj_jbj
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CasPxxJcptCdsysXwPxLwKxjFmjJbj record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cas_pxx_jcpt_cdsys_xw_px_lw_kxj_fmj_jbj
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CasPxxJcptCdsysXwPxLwKxjFmjJbj record);
}