package cn.arp.trend.repository.biz.auto;

import cn.arp.trend.entity.biz.CasPxxCzbk;

public interface CasPxxCzbkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cas_pxx_czbk
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cas_pxx_czbk
     *
     * @mbggenerated
     */
    int insert(CasPxxCzbk record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cas_pxx_czbk
     *
     * @mbggenerated
     */
    int insertSelective(CasPxxCzbk record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cas_pxx_czbk
     *
     * @mbggenerated
     */
    CasPxxCzbk selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cas_pxx_czbk
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CasPxxCzbk record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cas_pxx_czbk
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CasPxxCzbk record);
}