package cn.arp.trend.repository.biz.auto;

import cn.arp.trend.entity.biz.CasStatsScienceActivities;

public interface CasStatsScienceActivitiesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_cas_stats_science_activities
     *
     * @mbggenerated
     */
    int insert(CasStatsScienceActivities record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table v_cas_stats_science_activities
     *
     * @mbggenerated
     */
    int insertSelective(CasStatsScienceActivities record);
}