package cn.arp.trend.repository.biz.auto;

import cn.arp.trend.entity.biz.IcCome;

public interface IcComeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_come
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_come
     *
     * @mbggenerated
     */
    int insert(IcCome record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_come
     *
     * @mbggenerated
     */
    int insertSelective(IcCome record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_come
     *
     * @mbggenerated
     */
    IcCome selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_come
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(IcCome record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_come
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(IcCome record);
}