package cn.arp.trend.repository.biz.auto;

import cn.arp.trend.entity.biz.IcGo;

public interface IcGoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_go
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_go
     *
     * @mbggenerated
     */
    int insert(IcGo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_go
     *
     * @mbggenerated
     */
    int insertSelective(IcGo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_go
     *
     * @mbggenerated
     */
    IcGo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_go
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(IcGo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ic_go
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(IcGo record);
}