package cn.arp.trend.repository.biz.auto;

import cn.arp.trend.entity.biz.RefEduGraduation;

public interface RefEduGraduationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ref_edu_graduation
     *
     * @mbggenerated
     */
    int insert(RefEduGraduation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ref_edu_graduation
     *
     * @mbggenerated
     */
    int insertSelective(RefEduGraduation record);
}