package cn.arp.trend.repository.biz.auto;

import cn.arp.trend.entity.biz.RefEduEnrollment;

public interface RefEduEnrollmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ref_edu_enrollment
     *
     * @mbggenerated
     */
    int insert(RefEduEnrollment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ref_edu_enrollment
     *
     * @mbggenerated
     */
    int insertSelective(RefEduEnrollment record);
}