package cn.arp.trend.repository.biz.auto;


import cn.arp.trend.entity.biz.RefOrgType;

public interface RefOrgTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ref_org_type
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ref_org_type
     *
     * @mbggenerated
     */
    int insert(RefOrgType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ref_org_type
     *
     * @mbggenerated
     */
    int insertSelective(RefOrgType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ref_org_type
     *
     * @mbggenerated
     */
    RefOrgType selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ref_org_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(RefOrgType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ref_org_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(RefOrgType record);
}