package cn.arp.trend.repository.biz.auto;

import cn.arp.trend.entity.biz.StatHcauthorsCount;

public interface StatHcauthorsCountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_hcauthors_count
     *
     * @mbggenerated
     */
    int insert(StatHcauthorsCount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_hcauthors_count
     *
     * @mbggenerated
     */
    int insertSelective(StatHcauthorsCount record);
}