package cn.arp.trend.repository.biz.auto;

import cn.arp.trend.entity.biz.StatArpStaffDuty;

public interface StatArpStaffDutyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_arp_staff_duty
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_arp_staff_duty
     *
     * @mbggenerated
     */
    int insert(StatArpStaffDuty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_arp_staff_duty
     *
     * @mbggenerated
     */
    int insertSelective(StatArpStaffDuty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_arp_staff_duty
     *
     * @mbggenerated
     */
    StatArpStaffDuty selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_arp_staff_duty
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(StatArpStaffDuty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_arp_staff_duty
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(StatArpStaffDuty record);
}