package cn.arp.trend.repository.biz.auto;

import cn.arp.trend.entity.biz.StatTeacherStudent;

public interface StatTeacherStudentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_teacher_student
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_teacher_student
     *
     * @mbggenerated
     */
    int insert(StatTeacherStudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_teacher_student
     *
     * @mbggenerated
     */
    int insertSelective(StatTeacherStudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_teacher_student
     *
     * @mbggenerated
     */
    StatTeacherStudent selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_teacher_student
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(StatTeacherStudent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_teacher_student
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(StatTeacherStudent record);
}