package cn.arp.trend.repository.biz.auto;

import cn.arp.trend.entity.biz.StatArpStaffAge;

public interface StatArpStaffAgeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_arp_staff_age
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_arp_staff_age
     *
     * @mbggenerated
     */
    int insert(StatArpStaffAge record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_arp_staff_age
     *
     * @mbggenerated
     */
    int insertSelective(StatArpStaffAge record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_arp_staff_age
     *
     * @mbggenerated
     */
    StatArpStaffAge selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_arp_staff_age
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(StatArpStaffAge record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_arp_staff_age
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(StatArpStaffAge record);
}