package cn.arp.trend.repository.biz.auto;

import cn.arp.trend.entity.biz.StatArpStaffTechLevel;

public interface StatArpStaffTechLevelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_arp_staff_tech_level
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_arp_staff_tech_level
     *
     * @mbggenerated
     */
    int insert(StatArpStaffTechLevel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_arp_staff_tech_level
     *
     * @mbggenerated
     */
    int insertSelective(StatArpStaffTechLevel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_arp_staff_tech_level
     *
     * @mbggenerated
     */
    StatArpStaffTechLevel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_arp_staff_tech_level
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(StatArpStaffTechLevel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_arp_staff_tech_level
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(StatArpStaffTechLevel record);
}