package cn.arp.trend.repository.biz.auto;

import cn.arp.trend.entity.biz.StatCasTalentsProgram;

public interface StatCasTalentsProgramMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_cas_talents_program
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_cas_talents_program
     *
     * @mbggenerated
     */
    int insert(StatCasTalentsProgram record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_cas_talents_program
     *
     * @mbggenerated
     */
    int insertSelective(StatCasTalentsProgram record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_cas_talents_program
     *
     * @mbggenerated
     */
    StatCasTalentsProgram selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_cas_talents_program
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(StatCasTalentsProgram record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_cas_talents_program
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(StatCasTalentsProgram record);
}