package cn.arp.trend.repository.biz.auto;

import cn.arp.trend.entity.biz.StatChinaAward10yearFinalCount;

public interface StatChinaAward10yearFinalCountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_china_award_10year_final_count
     *
     * @mbggenerated
     */
    int insert(StatChinaAward10yearFinalCount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_china_award_10year_final_count
     *
     * @mbggenerated
     */
    int insertSelective(StatChinaAward10yearFinalCount record);
}