package cn.arp.trend.repository.biz.auto;

import cn.arp.trend.entity.biz.StatArpFinBudgetExecute;

public interface StatArpFinBudgetExecuteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_arp_fin_budget_execute
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_arp_fin_budget_execute
     *
     * @mbggenerated
     */
    int insert(StatArpFinBudgetExecute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_arp_fin_budget_execute
     *
     * @mbggenerated
     */
    int insertSelective(StatArpFinBudgetExecute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_arp_fin_budget_execute
     *
     * @mbggenerated
     */
    StatArpFinBudgetExecute selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_arp_fin_budget_execute
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(StatArpFinBudgetExecute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_arp_fin_budget_execute
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(StatArpFinBudgetExecute record);
}