package cn.arp.trend.repository.biz.auto;

import cn.arp.trend.entity.biz.StatArpFinIncome;

public interface StatArpFinIncomeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_arp_fin_income
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_arp_fin_income
     *
     * @mbggenerated
     */
    int insert(StatArpFinIncome record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_arp_fin_income
     *
     * @mbggenerated
     */
    int insertSelective(StatArpFinIncome record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_arp_fin_income
     *
     * @mbggenerated
     */
    StatArpFinIncome selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_arp_fin_income
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(StatArpFinIncome record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_arp_fin_income
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(StatArpFinIncome record);
}