package cn.arp.trend.repository.biz.auto;

import cn.arp.trend.entity.biz.StatArpFinAsset;

public interface StatArpFinAssetMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_arp_fin_asset
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_arp_fin_asset
     *
     * @mbggenerated
     */
    int insert(StatArpFinAsset record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_arp_fin_asset
     *
     * @mbggenerated
     */
    int insertSelective(StatArpFinAsset record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_arp_fin_asset
     *
     * @mbggenerated
     */
    StatArpFinAsset selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_arp_fin_asset
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(StatArpFinAsset record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_arp_fin_asset
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(StatArpFinAsset record);
}