package cn.arp.trend.repository.biz.auto;

import cn.arp.trend.entity.biz.StatPatentNew;

public interface StatPatentNewMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_patent_new
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_patent_new
     *
     * @mbggenerated
     */
    int insert(StatPatentNew record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_patent_new
     *
     * @mbggenerated
     */
    int insertSelective(StatPatentNew record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_patent_new
     *
     * @mbggenerated
     */
    StatPatentNew selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_patent_new
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(StatPatentNew record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_patent_new
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(StatPatentNew record);
}