package cn.arp.trend.repository.biz.auto;

import cn.arp.trend.entity.biz.StatArpStaffEducation;

public interface StatArpStaffEducationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_arp_staff_education
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_arp_staff_education
     *
     * @mbggenerated
     */
    int insert(StatArpStaffEducation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_arp_staff_education
     *
     * @mbggenerated
     */
    int insertSelective(StatArpStaffEducation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_arp_staff_education
     *
     * @mbggenerated
     */
    StatArpStaffEducation selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_arp_staff_education
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(StatArpStaffEducation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_arp_staff_education
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(StatArpStaffEducation record);
}