package cn.arp.trend.repository.biz.auto;

import cn.arp.trend.entity.biz.StatMostProject;

public interface StatMostProjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_most_project
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_most_project
     *
     * @mbggenerated
     */
    int insert(StatMostProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_most_project
     *
     * @mbggenerated
     */
    int insertSelective(StatMostProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_most_project
     *
     * @mbggenerated
     */
    StatMostProject selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_most_project
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(StatMostProject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_most_project
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(StatMostProject record);
}