package cn.arp.trend.repository.biz.auto;

import cn.arp.trend.entity.biz.StatArpStaffPost;

public interface StatArpStaffPostMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_arp_staff_post
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_arp_staff_post
     *
     * @mbggenerated
     */
    int insert(StatArpStaffPost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_arp_staff_post
     *
     * @mbggenerated
     */
    int insertSelective(StatArpStaffPost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_arp_staff_post
     *
     * @mbggenerated
     */
    StatArpStaffPost selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_arp_staff_post
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(StatArpStaffPost record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_arp_staff_post
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(StatArpStaffPost record);
}