package cn.arp.trend.repository.biz.auto;

import cn.arp.trend.entity.biz.StatCasPaper;

public interface StatCasPaperMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_cas_paper
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_cas_paper
     *
     * @mbggenerated
     */
    int insert(StatCasPaper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_cas_paper
     *
     * @mbggenerated
     */
    int insertSelective(StatCasPaper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_cas_paper
     *
     * @mbggenerated
     */
    StatCasPaper selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_cas_paper
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(StatCasPaper record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_cas_paper
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(StatCasPaper record);
}