package cn.arp.trend.repository.biz.auto;

import cn.arp.trend.entity.biz.TempCasStaffForRencaicount;

public interface TempCasStaffForRencaicountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temp_cas_staff_for_rencaicount
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temp_cas_staff_for_rencaicount
     *
     * @mbggenerated
     */
    int insert(TempCasStaffForRencaicount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temp_cas_staff_for_rencaicount
     *
     * @mbggenerated
     */
    int insertSelective(TempCasStaffForRencaicount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temp_cas_staff_for_rencaicount
     *
     * @mbggenerated
     */
    TempCasStaffForRencaicount selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temp_cas_staff_for_rencaicount
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TempCasStaffForRencaicount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table temp_cas_staff_for_rencaicount
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TempCasStaffForRencaicount record);
}