package cn.arp.trend.repository.biz.auto;

import cn.arp.trend.entity.biz.UpdateFrequency;

public interface UpdateFrequencyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table update_frequency
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table update_frequency
     *
     * @mbggenerated
     */
    int insert(UpdateFrequency record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table update_frequency
     *
     * @mbggenerated
     */
    int insertSelective(UpdateFrequency record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table update_frequency
     *
     * @mbggenerated
     */
    UpdateFrequency selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table update_frequency
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(UpdateFrequency record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table update_frequency
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(UpdateFrequency record);
}