package cn.arp.trend.repository.biz.manual;

import cn.arp.trend.entity.biz.StatChinaAward10yearFinalCount;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface StatChinaAward10yearFinalCountManualMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_china_award_10year_final_count
     *
     * @mbggenerated
     */
    int insert(StatChinaAward10yearFinalCount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stat_china_award_10year_final_count
     *
     * @mbggenerated
     */
    int insertSelective(StatChinaAward10yearFinalCount record);

    /**
     * 各所奖项
     * @param startYear
     * @param endYear
     * @return
     */
    List<StatChinaAward10yearFinalCount> queryByHjnf(@Param("startYear") String startYear,
                             @Param("endYear") String endYear);

    /**
     *
     * @return
     */
    List<Map<String, Object>> queryNationalAward1();

    /**
     *
     * @return
     */
    List<Map<String, Object>> queryNationalAward2();
}